// Functional Agent Workbench Requirements — Structured implementation seed
// Generated from functional-specs.ts + wave3-functional-specs.ts + Exa Parts 1-4
// Canonical source of truth for what each of 33 functional agents needs in its workspace.
//
// This file does NOT drive UI. It provides the typed map future workbench configs
// must satisfy. Each entry maps 1:1 to a canonical functional agent spec slug.

import type { FunctionalAgentArtifactType, FunctionalAgentActionRiskLevel } from "../runtime/types";

export type TemplateFamily =
  | "intake_workflow"
  | "analysis_report"
  | "batch_processor"
  | "monitoring_dashboard"
  | "compliance_screening"
  | "reconciliation_close"
  | "incident_response"
  | "campaign_planner"
  | "operations_dispatch"
  | "developer_tool"
  | "data_quality"
  | "risk_investigation"
  | "orchestration";

export interface WorkbenchRequirement {
  /** Canonical functional agent slug */
  slug: string;
  /** Display name from functional spec */
  name: string;
  /** Category from functional spec */
  category: string;
  /** UI layout archetype */
  templateFamily: TemplateFamily;
  /** Research sources covering this agent */
  researchSources: ("Part 1" | "Part 2" | "Part 3" | "Part 4" | "repo_spec_only")[];
  /** The object/event that initiates a run (not a blank chat) */
  primaryWorkflowObject: string;
  /** Step-by-step workflow */
  workflowSteps: string[];
  /** Specific workspace panels/modules */
  workspaceModules: string[];
  /** Domain-specific tools available to the agent */
  coreTools: string[];
  /** Concrete button/action labels users can invoke */
  primaryActions: string[];
  /** How mock/demo behavior works for each action */
  mockRunBehaviors: string[];
  /** Required input fields/types */
  requiredInputs: string[];
  /** Demo data fixture files needed */
  demoDataNeeded: string[];
  /** Result/display panels */
  resultPanels: string[];
  /** Output artifact types */
  artifactTypes: FunctionalAgentArtifactType[];
  /** Technology/integration targets (or `not provided`) */
  integrationTargets: string[];
  /** Actions that require human approval before execution */
  approvalGatedActions: string[];
  /** What the agent explicitly does NOT do (live/non-scope limits) */
  nonScopeLimits: string[];
  /** Eval case IDs from functional spec */
  evalCaseIds: string[];
  /** Minimum number of eval cases expected */
  evalCaseCount: number;
}

export const WORKBENCH_REQUIREMENTS: WorkbenchRequirement[] = [
  {
    slug: "backup-recovery-validation-agent",
    name: "Backup & Recovery Validation Agent",
    category: "infrastructure",
    templateFamily: "batch_processor",
    researchSources: ["Part 1", "repo_spec_only"],
    primaryWorkflowObject: "backup_validation_job",
    workflowSteps: [
      "Select backup job or schedule",
      "Ingest backup metadata (type, schedule, retention)",
      "Validate backup integrity against policy",
      "Check RPO/RTO compliance",
      "Identify gaps or failures",
      "Generate validation report",
      "Propose remediation actions",
    ],
    workspaceModules: [
      "Backup job selector",
      "Policy compliance panel",
      "RPO/RTO tracker",
      "Failure gap grid",
      "Validation report",
      "Remediation proposals",
    ],
    coreTools: [
      "backup_policy_audit",
      "rpo_rto_calculator",
      "integrity_check",
      "gap_analyzer",
      "validation_report_generator",
    ],
    primaryActions: [
      "Run backup validation",
      "Audit policy compliance",
      "Check RPO/RTO",
      "Identify coverage gaps",
      "Generate validation report",
      "Propose remediation steps",
    ],
    mockRunBehaviors: [
      "Run validation: scans mock backup metadata fixtures, flags missing/failed entries",
      "Audit policy: compares mock backup config against RPO/RTO rules",
      "Check RPO/RTO: computes delta from mock timestamps",
      "Identify gaps: marks days/hours with no backup record",
      "Generate report: produces structured validation report artifact",
      "Propose remediation: drafts action list with rationale (no execution)",
    ],
    requiredInputs: [
      "Backup metadata file (JSON/CSV)",
      "Backup policy definition",
      "RPO/RTO thresholds",
      "Retention schedule",
    ],
    demoDataNeeded: [
      "backup-manifest.json",
      "backup-policy.json",
      "failure-log.json",
      "retention-schedule.json",
    ],
    resultPanels: [
      "Policy compliance dashboard",
      "RPO/RTO compliance chart",
      "Failure gap grid",
      "Validation report",
      "Remediation proposals",
    ],
    artifactTypes: ["report", "checklist", "recommendation"],
    integrationTargets: ["Veeam", "Rubrik", "Cohesity", "Commvault", "AWS Backup", "Azure Backup"],
    approvalGatedActions: [
      "Execute backup restoration test",
      "Modify backup policy",
      "Trigger emergency backup",
    ],
    nonScopeLimits: [
      "No live backup connector",
      "No actual restoration execution",
      "No backup policy mutation",
      "No production data access",
    ],
    evalCaseIds: ["brv-eval-001", "brv-eval-002", "brv-eval-003", "brv-eval-004", "brv-eval-005", "brv-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "bi-analytics-agent",
    name: "BI Analytics Agent",
    category: "data",
    templateFamily: "analysis_report",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "analysis_question",
    workflowSteps: [
      "Upload dataset (CSV/JSON)",
      "Auto-profile columns and detect types",
      "Accept natural-language question",
      "Generate query/summary",
      "Produce chart + explanation",
      "Generate insight brief",
      "Suggest follow-up questions",
    ],
    workspaceModules: [
      "Dataset upload/selector",
      "Data profile panel",
      "Question composer",
      "Chart/table output",
      "Insight brief",
      "Source/metric explanation",
      "Follow-up suggestions",
      "Export report",
    ],
    coreTools: [
      "csv_parser",
      "column_profiler",
      "nl_to_aggregation",
      "chart_generator",
      "insight_brief_writer",
    ],
    primaryActions: [
      "Upload and profile dataset",
      "Ask question in plain language",
      "Generate chart",
      "Generate insight brief",
      "Suggest follow-up questions",
      "Export as markdown",
    ],
    mockRunBehaviors: [
      "Upload dataset: parses mock sales/inventory CSV, profiles columns, shows types/distributions",
      "Ask question: maps NL question to mock data aggregation, outputs table + chart",
      "Generate chart: produces line/bar/pie from mock data based on question",
      "Insight brief: writes structured markdown with findings, caveats, assumptions",
      "Suggest follow-ups: lists 3-5 next questions from detected patterns",
      "Export: generates downloadable markdown report",
    ],
    requiredInputs: [
      "Dataset upload (CSV/JSON)",
      "Natural language question",
    ],
    demoDataNeeded: [
      "sales-by-region.csv",
      "customer-churn.csv",
      "inventory-levels.json",
      "marketing-spend.csv",
    ],
    resultPanels: [
      "Data profile panel",
      "Chart/table output",
      "Insight brief (markdown)",
      "Follow-up question suggestions",
    ],
    artifactTypes: ["insight_brief", "analysis", "report", "export"],
    integrationTargets: ["Power BI", "Tableau Pulse", "ThoughtSpot Spotter", "Looker", "Metabase"],
    approvalGatedActions: [
      "Publish dashboard externally",
      "Share analysis with non-authorized users",
    ],
    nonScopeLimits: [
      "No live database connector",
      "No write-back to data warehouse",
      "No BI tool integration (mock only)",
      "No real-time data refresh",
    ],
    evalCaseIds: ["bi-eval-001", "bi-eval-002", "bi-eval-003", "bi-eval-004", "bi-eval-005", "bi-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "communications-messaging-agent",
    name: "Communications & Messaging Agent",
    category: "business-ops",
    templateFamily: "campaign_planner",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "message_campaign",
    workflowSteps: [
      "Define message objective and audience",
      "Select communication channels (email, SMS, WhatsApp, push)",
      "Generate compliant message variants per channel",
      "Preview drafts with brand controls",
      "Route through approval/review",
      "Schedule or release messages",
      "Track delivery and engagement",
    ],
    workspaceModules: [
      "Campaign brief composer",
      "Channel selector",
      "Message variant generator",
      "Brand compliance checker",
      "Approval queue",
      "Delivery tracker",
    ],
    coreTools: [
      "channel_selector",
      "message_variant_generator",
      "brand_compliance_checker",
      "approval_router",
      "delivery_tracker",
    ],
    primaryActions: [
      "Create message campaign",
      "Select communication channels",
      "Generate channel-specific variants",
      "Check brand compliance",
      "Submit for approval",
      "Preview delivery schedule",
    ],
    mockRunBehaviors: [
      "Create campaign: scaffolds campaign brief with objective, audience, channels",
      "Select channels: shows available channels with mock availability/limits",
      "Generate variants: creates per-channel drafts (SMS short, email long, WhatsApp friendly)",
      "Check compliance: runs against mock brand guidelines, flags issues",
      "Submit approval: queues for review, records approval decision",
      "Preview schedule: shows mock send timeline",
    ],
    requiredInputs: [
      "Campaign objective",
      "Target audience definition",
      "Message content/key points",
      "Selected channels",
    ],
    demoDataNeeded: [
      "message-templates.json",
      "brand-guidelines.json",
      "channel-capabilities.json",
      "audience-segments.json",
    ],
    resultPanels: [
      "Message variant previews",
      "Brand compliance report",
      "Campaign timeline",
      "Approval status",
    ],
    artifactTypes: ["draft", "approval_packet", "report"],
    integrationTargets: ["Twilio", "SendGrid", "Intercom", "HubSpot Marketing", "Klaviyo", "Braze"],
    approvalGatedActions: [
      "Send messages to real recipients",
      "Modify brand guidelines",
      "Override compliance flags",
    ],
    nonScopeLimits: [
      "No live message delivery",
      "No real recipient data",
      "No actual channel API calls",
      "No A/B test execution",
    ],
    evalCaseIds: ["cm-eval-001", "cm-eval-002", "cm-eval-003", "cm-eval-004", "cm-eval-005", "cm-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "customer-support-agent",
    name: "Customer Support Agent",
    category: "business-ops",
    templateFamily: "intake_workflow",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "support_ticket",
    workflowSteps: [
      "Intake support request / ticket",
      "Classify issue type and severity",
      "Search knowledge base for relevant articles",
      "Suggest matching solutions",
      "Draft reply with evidence citations",
      "Escalate if confidence is low",
      "Generate resolution summary",
    ],
    workspaceModules: [
      "Ticket intake form",
      "Issue classification panel",
      "KB search results",
      "Solution suggestions",
      "Reply composer",
      "Escalation flow",
      "Resolution summary",
    ],
    coreTools: [
      "ticket_classifier",
      "kb_search",
      "sentiment_analyzer",
      "reply_draft_generator",
      "escalation_router",
    ],
    primaryActions: [
      "Classify support ticket",
      "Search knowledge base",
      "Suggest solution",
      "Draft customer reply",
      "Route escalation",
      "Generate resolution summary",
    ],
    mockRunBehaviors: [
      "Classify ticket: assigns type/severity/urgency from mock ticket intake",
      "Search KB: retrieves relevant articles from mock knowledge base",
      "Suggest solution: ranks solutions by match confidence",
      "Draft reply: composes polite, accurate response with KB citations",
      "Route escalation: identifies high-severity tickets, proposes escalation path",
      "Generate summary: produces structured resolution summary artifact",
    ],
    requiredInputs: [
      "Customer inquiry text",
      "Product/service context",
      "Customer tier (optional)",
      "Previous ticket history (optional)",
    ],
    demoDataNeeded: [
      "sample-tickets.json",
      "knowledge-base-articles.json",
      "customer-profiles.json",
      "escalation-paths.json",
    ],
    resultPanels: [
      "Ticket classification display",
      "KB search results panel",
      "Reply draft preview",
      "Resolution summary",
    ],
    artifactTypes: ["report", "summary", "recommendation", "draft"],
    integrationTargets: ["Zendesk", "Intercom", "Gorgias", "Freshdesk", "Salesforce Service Cloud"],
    approvalGatedActions: [
      "Send reply to customer",
      "Close ticket",
      "Create KB article",
    ],
    nonScopeLimits: [
      "No live ticket system connector",
      "No actual message delivery",
      "No ticket mutation in production",
      "No live customer data access",
    ],
    evalCaseIds: ["csa-eval-001", "csa-eval-002", "csa-eval-003", "csa-eval-004", "csa-eval-005", "csa-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "developer-deployment-agent",
    name: "Developer Deployment Agent",
    category: "developer-tools",
    templateFamily: "developer_tool",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "deployment_job",
    workflowSteps: [
      "Select deployment environment and target",
      "Ingest deployment config and artifacts",
      "Run readiness checks (tests, approvals, gates)",
      "Validate infrastructure prerequisites",
      "Execute staged rollout plan",
      "Monitor deployment health",
      "Generate deployment report",
    ],
    workspaceModules: [
      "Deployment environment selector",
      "Readiness checklist",
      "Infra prerequisite validator",
      "Rollout stage tracker",
      "Health monitor dashboard",
      "Deployment report",
    ],
    coreTools: [
      "readiness_checker",
      "infra_validator",
      "rollout_planner",
      "health_monitor",
      "deployment_reporter",
    ],
    primaryActions: [
      "Run readiness checks",
      "Validate infrastructure",
      "Create rollout plan",
      "Monitor deployment health",
      "Generate deployment report",
      "Propose rollback plan",
    ],
    mockRunBehaviors: [
      "Readiness checks: validates mock test results, gate status, approval records",
      "Validate infra: checks mock cloud resource state against deployment requirements",
      "Create rollout: drafts staged rollout with canary/batch strategy",
      "Monitor health: simulates health check polling, flags anomalies",
      "Generate report: produces structured deployment report artifact",
      "Propose rollback: drafts rollback steps from mock deployment state",
    ],
    requiredInputs: [
      "Deployment configuration",
      "Environment target (staging/production)",
      "Artifact version/build ID",
      "Test results summary",
    ],
    demoDataNeeded: [
      "deployment-config.json",
      "test-results.json",
      "infra-state.json",
      "health-check-metrics.json",
    ],
    resultPanels: [
      "Readiness gates dashboard",
      "Rollout progress tracker",
      "Health metrics panel",
      "Deployment report",
    ],
    artifactTypes: ["report", "checklist", "recommendation", "plan"],
    integrationTargets: ["Harness", "CircleCI", "ArgoCD", "Spinnaker", "AWS CodeDeploy", "Octopus Deploy"],
    approvalGatedActions: [
      "Execute deployment",
      "Promote to production",
      "Rollback live deployment",
    ],
    nonScopeLimits: [
      "No live CI/CD connector",
      "No actual deployment execution",
      "No production mutation",
      "No infrastructure provisioning",
    ],
    evalCaseIds: ["dd-eval-001", "dd-eval-002", "dd-eval-003", "dd-eval-004", "dd-eval-005", "dd-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "developer-platform-agent",
    name: "Developer Platform Agent",
    category: "developer-tools",
    templateFamily: "developer_tool",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "developer_request",
    workflowSteps: [
      "Intake developer request (service catalog, onboarding, docs)",
      "Identify relevant service/component",
      "Query service catalog for metadata and ownership",
      "Retrieve documentation and runbook references",
      "Generate developer guide or response",
      "Route to appropriate team if needed",
      "Record request in developer log",
    ],
    workspaceModules: [
      "Service catalog explorer",
      "Developer request intake",
      "Documentation retriever",
      "Ownership/team panel",
      "Developer guide composer",
      "Request log",
    ],
    coreTools: [
      "service_catalog_search",
      "doc_retriever",
      "ownership_resolver",
      "guide_generator",
      "request_logger",
    ],
    primaryActions: [
      "Search service catalog",
      "Find service owners",
      "Retrieve documentation",
      "Generate onboarding guide",
      "Log developer request",
      "Route to team",
    ],
    mockRunBehaviors: [
      "Search catalog: queries mock service catalog for component info",
      "Find owners: resolves ownership from mock team/service mappings",
      "Retrieve docs: pulls relevant mock runbooks and READMEs",
      "Generate guide: composes onboarding/usage guide with catalog context",
      "Log request: records request in mock developer activity log",
      "Route to team: proposes routing based on ownership resolution",
    ],
    requiredInputs: [
      "Developer request/question",
      "Service or component name (optional)",
      "Developer role/context (optional)",
    ],
    demoDataNeeded: [
      "service-catalog.json",
      "team-ownership-map.json",
      "runbook-library.json",
      "onboarding-templates.json",
    ],
    resultPanels: [
      "Service catalog result panel",
      "Documentation panel",
      "Developer guide preview",
      "Request log panel",
    ],
    artifactTypes: ["report", "draft", "recommendation", "summary"],
    integrationTargets: ["Backstage", "Datadog IDP", "Port", "Cortex", "OpsLevel", "Atlassian Compass"],
    approvalGatedActions: [
      "Publish documentation changes",
      "Modify service ownership",
      "Create new service entry",
    ],
    nonScopeLimits: [
      "No live catalog connector",
      "No service provisioning",
      "No documentation write-back",
      "No team membership changes",
    ],
    evalCaseIds: ["devplat-eval-001", "devplat-eval-002", "devplat-eval-003", "devplat-eval-004", "devplat-eval-005", "devplat-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "document-workflow-agent",
    name: "Document Workflow Agent",
    category: "business-ops",
    templateFamily: "intake_workflow",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "document_review",
    workflowSteps: [
      "Ingest document for review",
      "Classify document type and purpose",
      "Extract key terms, dates, and clauses",
      "Compare against template/policy",
      "Identify redlines and deviations",
      "Route for approvals based on workflow",
      "Generate review summary and compliance notes",
    ],
    workspaceModules: [
      "Document upload/intake",
      "Document classification panel",
      "Term extraction panel",
      "Redline/compare view",
      "Approval workflow tracker",
      "Review summary",
    ],
    coreTools: [
      "document_classifier",
      "term_extractor",
      "redline_comparator",
      "compliance_checker",
      "approval_workflow_engine",
    ],
    primaryActions: [
      "Upload and classify document",
      "Extract key terms and clauses",
      "Compare against template",
      "Identify deviations/redlines",
      "Route for approval",
      "Generate review summary",
    ],
    mockRunBehaviors: [
      "Upload document: parses mock contract/agreement fixture, detects format",
      "Classify: identifies document as NDA, SOW, MSA, etc.",
      "Extract terms: pulls dates, parties, amounts, key clauses",
      "Compare: diffs against mock template, highlights differences",
      "Route approval: identifies required reviewers based on document type",
      "Generate summary: produces structured review summary artifact",
    ],
    requiredInputs: [
      "Document file (PDF/DOCX/TXT)",
      "Document type (optional, auto-detected)",
      "Comparison template (optional)",
      "Approval workflow (optional)",
    ],
    demoDataNeeded: [
      "sample-nda.pdf",
      "sample-msa.docx",
      "template-nda.json",
      "approval-workflow-config.json",
    ],
    resultPanels: [
      "Document classification panel",
      "Term extraction grid",
      "Redline/compare view",
      "Review summary",
      "Approval status tracker",
    ],
    artifactTypes: ["report", "checklist", "recommendation", "draft", "approval_packet"],
    integrationTargets: ["DocuSign", "Ironclad", "PandaDoc", "Adobe Sign", "ContractPodAI", "Juro"],
    approvalGatedActions: [
      "Send document for external signature",
      "Execute contract",
      "Modify template library",
    ],
    nonScopeLimits: [
      "No live e-signature integration",
      "No contract execution",
      "No legal document filing",
      "No template library management",
    ],
    evalCaseIds: ["dw-eval-001", "dw-eval-002", "dw-eval-003", "dw-eval-004", "dw-eval-005", "dw-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "experimentation-agent",
    name: "Experimentation Agent",
    category: "data",
    templateFamily: "analysis_report",
    researchSources: ["repo_spec_only"],
    primaryWorkflowObject: "experiment_design",
    workflowSteps: [
      "Define experiment hypothesis and success metrics",
      "Design experiment methodology and sample size",
      "Load or input experiment data",
      "Compute statistical significance",
      "Visualize results with confidence intervals",
      "Generate experiment brief with recommendations",
      "Flag confounding factors and caveats",
    ],
    workspaceModules: [
      "Hypothesis composer",
      "Sample size calculator",
      "Data input panel",
      "Statistical test engine",
      "Results visualization",
      "Experiment brief",
      "Caveats and limitations",
    ],
    coreTools: [
      "hypothesis_formulator",
      "sample_size_calculator",
      "statistical_test_runner",
      "confidence_interval_visualizer",
      "experiment_brief_writer",
    ],
    primaryActions: [
      "Define experiment hypothesis",
      "Calculate required sample size",
      "Run statistical test",
      "Generate results visualization",
      "Create experiment brief",
      "Propose next steps",
    ],
    mockRunBehaviors: [
      "Define hypothesis: scaffolds null/alternative hypothesis from user input",
      "Calculate sample: computes sample size needed from mock effect size and power",
      "Run test: performs mock t-test/chi-square/ANOVA on input data",
      "Visualize: produces chart with confidence intervals",
      "Brief: writes structured experiment brief with methodology and caveats",
      "Propose next: suggests follow-up experiments based on findings",
    ],
    requiredInputs: [
      "Experiment hypothesis",
      "Success metric definition",
      "Experiment data (CSV)",
      "Control/variant group identifiers",
    ],
    demoDataNeeded: [
      "ab-test-results.csv",
      "experiment-config.json",
      "statistical-significance-tables.json",
      "experiment-report-template.json",
    ],
    resultPanels: [
      "Hypothesis summary panel",
      "Statistical test results",
      "Confidence interval chart",
      "Experiment brief",
    ],
    artifactTypes: ["report", "analysis", "insight_brief", "recommendation"],
    integrationTargets: ["Statsig", "LaunchDarkly", "Optimizely", "Google Optimize", "Eppo"],
    approvalGatedActions: [
      "Ship winning variant to production",
      "Modify experiment configuration on live test",
    ],
    nonScopeLimits: [
      "No live feature flag connector",
      "No production variant shipping",
      "No real-time experiment monitoring",
      "No live user bucketing",
    ],
    evalCaseIds: ["exp-eval-001", "exp-eval-002", "exp-eval-003", "exp-eval-004", "exp-eval-005", "exp-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "it-service-desk-agent",
    name: "IT Service Desk Agent",
    category: "business-ops",
    templateFamily: "intake_workflow",
    researchSources: ["Part 1", "repo_spec_only"],
    primaryWorkflowObject: "it_ticket",
    workflowSteps: [
      "Intake IT service request or incident",
      "Classify ticket type and priority",
      "Search service catalog and KB for known solutions",
      "Check user entitlements and asset context",
      "Draft resolution or workaround",
      "Route escalation if needed (L1→L2→L3)",
      "Generate resolution summary and close notes",
    ],
    workspaceModules: [
      "Ticket intake form",
      "Ticket classification panel",
      "Service catalog search",
      "Knowledge base panel",
      "User/asset context panel",
      "Resolution composer",
      "Escalation flow",
    ],
    coreTools: [
      "ticket_classifier",
      "service_catalog_searcher",
      "kb_searcher",
      "entitlement_checker",
      "resolution_draft_generator",
      "escalation_router",
    ],
    primaryActions: [
      "Classify IT ticket",
      "Search service catalog",
      "Look up knowledge base",
      "Draft resolution",
      "Route escalation",
      "Generate resolution summary",
    ],
    mockRunBehaviors: [
      "Classify: assigns category/priority/impact from mock IT ticket intake",
      "Search catalog: queries mock IT service catalog for relevant services",
      "Look up KB: retrieves matching mock KB articles",
      "Draft resolution: composes step-by-step resolution with KB citations",
      "Route escalation: identifies tickets needing L2/L3, proposes path",
      "Generate summary: produces structured close notes artifact",
    ],
    requiredInputs: [
      "IT issue description",
      "User/employee identifier",
      "Affected asset/service",
      "Priority (optional, auto-detected)",
    ],
    demoDataNeeded: [
      "it-tickets.json",
      "service-catalog-it.json",
      "knowledge-base-it.json",
      "user-entitlements.json",
      "asset-inventory.json",
    ],
    resultPanels: [
      "Ticket classification panel",
      "Service catalog results",
      "KB search results",
      "Resolution draft preview",
      "Escalation path panel",
    ],
    artifactTypes: ["report", "checklist", "recommendation", "summary"],
    integrationTargets: ["ServiceNow", "Jira Service Management", "BMC Helix", "Freshservice", "Zendesk ITSM"],
    approvalGatedActions: [
      "Close ticket in production",
      "Create new KB article",
      "Modify service catalog entry",
      "Grant elevated access",
    ],
    nonScopeLimits: [
      "No live ITSM connector",
      "No ticket mutation in production",
      "No service catalog write-back",
      "No user access changes",
    ],
    evalCaseIds: ["itsm-eval-001", "itsm-eval-002", "itsm-eval-003", "itsm-eval-004", "itsm-eval-005", "itsm-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "project-work-agent",
    name: "Project Work Agent",
    category: "business-ops",
    templateFamily: "operations_dispatch",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "project_update",
    workflowSteps: [
      "Intake project context (tasks, timelines, team)",
      "Analyze current project status against plan",
      "Identify blockers, at-risk items, and delays",
      "Generate stakeholder status report",
      "Create action plan with owner assignments",
      "Track dependencies across workstreams",
      "Propose schedule adjustments",
    ],
    workspaceModules: [
      "Project context intake",
      "Status dashboard",
      "Blocker tracker",
      "Dependency map",
      "Action plan panel",
      "Stakeholder report composer",
      "Schedule adjustment panel",
    ],
    coreTools: [
      "status_summarizer",
      "blocker_detector",
      "dependency_mapper",
      "stakeholder_report_generator",
      "action_plan_creator",
    ],
    primaryActions: [
      "Summarize project status",
      "Identify blockers",
      "Map dependencies",
      "Create action plan",
      "Generate stakeholder report",
      "Propose schedule adjustment",
    ],
    mockRunBehaviors: [
      "Summarize status: ingests mock project status data, produces health summary",
      "Identify blockers: flags blocked/at-risk tasks with rationale",
      "Map dependencies: builds dependency graph from mock task linkages",
      "Create action plan: drafts next-step actions with owner assignments",
      "Generate report: produces structured stakeholder-ready status report",
      "Propose adjustment: suggests timeline changes for at-risk milestones",
    ],
    requiredInputs: [
      "Project status data",
      "Task list and assignments",
      "Timeline/schedule",
      "Team roster",
    ],
    demoDataNeeded: [
      "project-status.json",
      "task-assignments.json",
      "project-timeline.json",
      "team-roster.json",
    ],
    resultPanels: [
      "Project health dashboard",
      "Blocker tracker panel",
      "Dependency map view",
      "Stakeholder report preview",
    ],
    artifactTypes: ["report", "checklist", "plan", "analysis"],
    integrationTargets: ["Asana", "Monday.com", "ClickUp", "Linear", "Jira Work Management", "Notion"],
    approvalGatedActions: [
      "Update live project tasks",
      "Reassign work to team members",
      "Modify project timeline in source system",
    ],
    nonScopeLimits: [
      "No live project management connector",
      "No task system mutation",
      "No team member notification",
      "No calendar scheduling",
    ],
    evalCaseIds: ["pw-eval-001", "pw-eval-002", "pw-eval-003", "pw-eval-004", "pw-eval-005", "pw-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "recruiting-automation-agent",
    name: "Recruiting Automation Agent",
    category: "hr",
    templateFamily: "intake_workflow",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "req_or_candidate",
    workflowSteps: [
      "Intake job requisition or candidate profile",
      "Match candidates to open reqs with scoring",
      "Screen resumes against job requirements",
      "Generate outreach/personalization for candidates",
      "Schedule and coordinate interviews",
      "Track pipeline stage and status",
      "Generate hiring committee brief",
    ],
    workspaceModules: [
      "Job requisition viewer",
      "Candidate matching panel",
      "Resume screening panel",
      "Outreach composer",
      "Interview coordinator",
      "Pipeline tracker",
      "Hiring brief composer",
    ],
    coreTools: [
      "candidate_matcher",
      "resume_screener",
      "outreach_generator",
      "interview_scheduler",
      "pipeline_tracker",
      "hiring_brief_writer",
    ],
    primaryActions: [
      "Match candidates to requisition",
      "Screen resume against job",
      "Generate outreach message",
      "Coordinate interview schedule",
      "Track hiring pipeline",
      "Create hiring committee brief",
    ],
    mockRunBehaviors: [
      "Match candidates: scores mock candidates against mock job requirements",
      "Screen resume: extracts skills, experience, education against job criteria",
      "Generate outreach: composes personalized candidate message with role context",
      "Coordinate schedule: proposes interview slots from mock availability",
      "Track pipeline: updates mock stage status with notes",
      "Create brief: produces structured hiring committee brief artifact",
    ],
    requiredInputs: [
      "Job requisition details",
      "Candidate profile/resume",
      "Selection criteria/requirements",
      "Interviewer availability (optional)",
    ],
    demoDataNeeded: [
      "job-requisitions.json",
      "candidate-profiles.json",
      "resume-sample.json",
      "requirement-matrix.json",
      "interviewer-availability.json",
    ],
    resultPanels: [
      "Candidate match score panel",
      "Resume screening results",
      "Outreach message preview",
      "Interview schedule panel",
    ],
    artifactTypes: ["report", "draft", "checklist", "recommendation"],
    integrationTargets: ["Greenhouse", "Lever", "Workday Recruiting", "Ashby", "Gem", "LinkedIn Recruiter"],
    approvalGatedActions: [
      "Send outreach to real candidate",
      "Schedule interview in production calendar",
      "Advance candidate to next stage in ATS",
      "Generate offer letter",
    ],
    nonScopeLimits: [
      "No live ATS connector",
      "No candidate communication",
      "No calendar integration",
      "No offer letter execution",
    ],
    evalCaseIds: ["ra-eval-001", "ra-eval-002", "ra-eval-003", "ra-eval-004", "ra-eval-005", "ra-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "workflow-automation-agent",
    name: "Workflow Automation Agent",
    category: "business-ops",
    templateFamily: "orchestration",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "automation_request",
    workflowSteps: [
      "Analyze process or workflow for automation opportunities",
      "Map process steps, triggers, and handoffs",
      "Identify bottlenecks and manual touchpoints",
      "Design automation flow with decision gates",
      "Route proposed actions through approval",
      "Generate automation deployment plan",
      "Create monitoring and alerting configuration",
    ],
    workspaceModules: [
      "Process mapper",
      "Bottleneck analyzer",
      "Automation flow designer",
      "Approval gate configurator",
      "Deployment planner",
      "Monitoring config panel",
    ],
    coreTools: [
      "process_analyzer",
      "bottleneck_detector",
      "automation_flow_designer",
      "approval_gate_configurator",
      "deployment_planner",
      "monitoring_configurator",
    ],
    primaryActions: [
      "Analyze process workflow",
      "Map process steps and triggers",
      "Identify bottlenecks",
      "Design automation flow",
      "Configure approval gates",
      "Generate deployment plan",
    ],
    mockRunBehaviors: [
      "Analyze process: ingests mock process description, identifies automation candidates",
      "Map steps: produces step-by-step process map with triggers and handoffs",
      "Identify bottlenecks: flags manual touchpoints and delay-prone steps",
      "Design flow: creates visual automation flow with decision nodes and actions",
      "Configure gates: sets up approval checkpoints for risky steps",
      "Generate plan: produces deployment plan with rollback path",
    ],
    requiredInputs: [
      "Process description or workflow data",
      "Trigger conditions",
      "Decision rules",
      "Integration points",
    ],
    demoDataNeeded: [
      "process-maps.json",
      "trigger-definitions.json",
      "automation-templates.json",
      "approval-gate-configs.json",
      "connector-catalog.json",
    ],
    resultPanels: [
      "Process map viewer",
      "Bottleneck analysis panel",
      "Automation flow diagram",
      "Deployment plan panel",
    ],
    artifactTypes: ["plan", "report", "recommendation", "checklist"],
    integrationTargets: ["Zapier", "Make", "n8n", "Temporal", "Camunda", "Pipedream"],
    approvalGatedActions: [
      "Activate automation in production",
      "Connect to live trigger sources",
      "Execute data mutation actions",
    ],
    nonScopeLimits: [
      "No live workflow engine connector",
      "No automation execution",
      "No trigger/action integration",
      "No production workflow mutation",
    ],
    evalCaseIds: ["wa-eval-001", "wa-eval-002", "wa-eval-003", "wa-eval-004", "wa-eval-005", "wa-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "api-gateway-agent",
    name: "API Gateway Agent",
    category: "infrastructure",
    templateFamily: "monitoring_dashboard",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "api_gateway_alert",
    workflowSteps: [
      "Ingest API traffic data or policy alert",
      "Analyze request rates, latency, error patterns",
      "Detect policy violations or compliance gaps",
      "Identify shadow/undocumented APIs",
      "Generate API health report",
      "Propose policy adjustments",
      "Create rate limit or routing recommendations",
    ],
    workspaceModules: [
      "API traffic dashboard",
      "Policy compliance panel",
      "Shadow API detector",
      "Error/latency chart",
      "API health report",
      "Policy recommendation panel",
    ],
    coreTools: [
      "api_traffic_analyzer",
      "policy_compliance_checker",
      "shadow_api_detector",
      "health_report_generator",
      "policy_recommender",
    ],
    primaryActions: [
      "Analyze API traffic",
      "Scan for policy violations",
      "Detect shadow APIs",
      "Generate API health report",
      "Propose policy adjustments",
      "Recommend rate limits",
    ],
    mockRunBehaviors: [
      "Analyze traffic: computes mock request stats, latency, error rates",
      "Scan violations: checks mock API config against policy rules",
      "Detect shadow: identifies undocumented endpoints from mock traffic log",
      "Generate report: produces structured API health report artifact",
      "Propose policy: drafts policy adjustments with rationale",
      "Recommend limits: suggests rate limits based on mock usage patterns",
    ],
    requiredInputs: [
      "API traffic data/logs",
      "API policy configuration",
      "Service/endpoint catalog",
      "Rate limit rules",
    ],
    demoDataNeeded: [
      "api-traffic-log.json",
      "api-policy-config.json",
      "endpoint-catalog.json",
      "rate-limit-rules.json",
    ],
    resultPanels: [
      "API traffic metrics panel",
      "Policy compliance dashboard",
      "Shadow API list",
      "API health report",
    ],
    artifactTypes: ["report", "analysis", "recommendation"],
    integrationTargets: ["Kong", "Tyk", "Apigee", "AWS API Gateway", "Gravitee", "Traefik"],
    approvalGatedActions: [
      "Apply policy change to live gateway",
      "Rate-limit live API",
      "Block shadow API endpoint",
    ],
    nonScopeLimits: [
      "No live API gateway connector",
      "No policy enforcement",
      "No traffic routing changes",
      "No endpoint blocking",
    ],
    evalCaseIds: ["apigw-eval-001", "apigw-eval-002", "apigw-eval-003", "apigw-eval-004", "apigw-eval-005", "apigw-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "cicd-pipeline-agent",
    name: "CI/CD Pipeline Agent",
    category: "developer-tools",
    templateFamily: "developer_tool",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "pipeline_run",
    workflowSteps: [
      "Ingest pipeline run log or build output",
      "Classify failure type (test, build, deploy, dependency)",
      "Identify root cause from log analysis",
      "Check release readiness gates",
      "Suggest fix or remediation path",
      "Generate failure triage report",
      "Propose rollback or rerun action",
    ],
    workspaceModules: [
      "Pipeline run selector",
      "Failure classification panel",
      "Root cause analysis panel",
      "Suggested fix panel",
      "Release readiness checklist",
      "Rollback plan panel",
    ],
    coreTools: [
      "pipeline_log_parser",
      "failure_classifier",
      "root_cause_analyzer",
      "release_gate_checker",
      "fix_suggester",
      "rollback_planner",
    ],
    primaryActions: [
      "Inspect failed pipeline run",
      "Classify failure type",
      "Identify root cause",
      "Suggest fix",
      "Check release readiness",
      "Generate rollback plan",
    ],
    mockRunBehaviors: [
      "Inspect run: parses mock pipeline log, identifies failed stage and job",
      "Classify failure: assigns to test/build/deploy/dependency category",
      "Root cause: isolates error line and correlates with recent changes",
      "Suggest fix: proposes specific code/test/config fix",
      "Check readiness: validates all gates against mock criteria",
      "Generate rollback: drafts step-by-step rollback plan with verification",
    ],
    requiredInputs: [
      "Pipeline run log",
      "Build configuration",
      "Test results summary",
      "Changed files list",
    ],
    demoDataNeeded: [
      "successful-build.log",
      "test-failure.log",
      "dependency-failure.log",
      "rollback-scenario.log",
    ],
    resultPanels: [
      "Failure classification panel",
      "Root cause analysis",
      "Release readiness checklist",
      "Rollback plan preview",
    ],
    artifactTypes: ["report", "checklist", "recommendation", "analysis"],
    integrationTargets: ["GitHub Actions", "GitLab CI", "Jenkins", "CircleCI", "Buildkite"],
    approvalGatedActions: [
      "Rerun failed deployment",
      "Approve production release",
      "Rollback live deployment",
    ],
    nonScopeLimits: [
      "No live CI/CD connector",
      "No job rerun execution",
      "No deployment approval in production",
      "No release gating enforcement",
    ],
    evalCaseIds: ["cicd-eval-001", "cicd-eval-002", "cicd-eval-003", "cicd-eval-004", "cicd-eval-005", "cicd-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "crm-engagement-agent",
    name: "CRM Engagement Agent",
    category: "business-ops",
    templateFamily: "operations_dispatch",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "account_or_lead",
    workflowSteps: [
      "View account or lead record context",
      "Assess pipeline health and engagement score",
      "Identify at-risk accounts or stale leads",
      "Generate account brief with talking points",
      "Draft follow-up or nurture message",
      "Propose CRM record update",
      "Submit for approval before write-back",
    ],
    workspaceModules: [
      "Account/lead selector",
      "Pipeline health dashboard",
      "Engagement score panel",
      "Account brief composer",
      "Message draft panel",
      "CRM update proposal panel",
      "Approval queue",
    ],
    coreTools: [
      "pipeline_health_analyzer",
      "engagement_scorer",
      "account_brief_writer",
      "message_draft_generator",
      "crm_update_proposer",
    ],
    primaryActions: [
      "View account health",
      "Score engagement",
      "Generate account brief",
      "Draft follow-up message",
      "Propose CRM update",
      "Submit update for approval",
    ],
    mockRunBehaviors: [
      "View health: loads mock account with pipeline stage, deal value, last contact",
      "Score engagement: computes mock score from activity history and response rates",
      "Account brief: generates structured brief with talking points, risks, next steps",
      "Draft message: composes personalized follow-up with account context",
      "Propose update: generates CRM field changes with before/after",
      "Submit approval: routes proposed changes through approval gate",
    ],
    requiredInputs: [
      "Account or lead identifier",
      "Pipeline stage info",
      "Recent activity data",
      "CRM field data",
    ],
    demoDataNeeded: [
      "account-records.json",
      "pipeline-stages.json",
      "activity-history.json",
      "message-templates.json",
      "engagement-scores.json",
    ],
    resultPanels: [
      "Account health dashboard",
      "Engagement score chart",
      "Account brief preview",
      "CRM update proposal panel",
    ],
    artifactTypes: ["report", "draft", "recommendation", "analysis"],
    integrationTargets: ["Salesforce", "HubSpot", "Pipedrive", "Zoho CRM", "Microsoft Dynamics 365"],
    approvalGatedActions: [
      "Update CRM record in production",
      "Send follow-up to customer",
      "Modify pipeline stage",
    ],
    nonScopeLimits: [
      "No live CRM connector",
      "No CRM write-back",
      "No customer communication",
      "No deal modification",
    ],
    evalCaseIds: ["crm-eval-001", "crm-eval-002", "crm-eval-003", "crm-eval-004", "crm-eval-005", "crm-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "data-governance-catalog-agent",
    name: "Data Governance & Catalog Agent",
    category: "data",
    templateFamily: "data_quality",
    researchSources: ["Part 2", "Part 3", "repo_spec_only"],
    primaryWorkflowObject: "data_asset",
    workflowSteps: [
      "Search or browse data catalog",
      "View dataset metadata, lineage, and classification",
      "Check data quality and freshness",
      "Identify PII/sensitive data exposure",
      "Review access policies and ownership",
      "Generate governance report",
      "Propose remediation for violations",
    ],
    workspaceModules: [
      "Catalog search/browse panel",
      "Dataset metadata panel",
      "Lineage graph viewer",
      "Data classification panel",
      "Access policy auditer",
      "Governance report",
    ],
    coreTools: [
      "catalog_searcher",
      "lineage_tracer",
      "data_classifier",
      "pii_detector",
      "policy_auditer",
      "governance_reporter",
    ],
    primaryActions: [
      "Search data catalog",
      "View dataset lineage",
      "Classify data sensitivity",
      "Detect PII exposure",
      "Audit access policies",
      "Generate governance report",
    ],
    mockRunBehaviors: [
      "Search catalog: queries mock catalog for datasets by name/domain/owner",
      "View lineage: renders mock upstream/downstream dependency graph",
      "Classify data: scans mock schema for PII, financial, health data columns",
      "Detect PII: flags columns containing mock PII patterns",
      "Audit policies: checks mock access rules against data classification",
      "Generate report: produces structured governance compliance report",
    ],
    requiredInputs: [
      "Dataset identifier",
      "Schema definition",
      "Access policy configuration",
      "Classification rules",
    ],
    demoDataNeeded: [
      "catalog-entries.json",
      "lineage-graph.json",
      "classification-rules.json",
      "access-policies.json",
      "pii-patterns.json",
    ],
    resultPanels: [
      "Catalog search results",
      "Lineage graph viewer",
      "Classification report panel",
      "Governance compliance report",
    ],
    artifactTypes: ["report", "checklist", "risk_matrix", "recommendation"],
    integrationTargets: ["Alation", "Collibra", "Atlan", "DataHub", "Amundsen", "Informatica", "Monte Carlo"],
    approvalGatedActions: [
      "Modify data classification",
      "Change access policy",
      "Delete catalog entry",
    ],
    nonScopeLimits: [
      "No live catalog connector",
      "No schema modification",
      "No access policy enforcement",
      "No data deletion",
    ],
    evalCaseIds: ["dgc-eval-001", "dgc-eval-002", "dgc-eval-003", "dgc-eval-004", "dgc-eval-005", "dgc-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "data-pipeline-agent",
    name: "Data Pipeline Agent",
    category: "data",
    templateFamily: "data_quality",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "pipeline_job",
    workflowSteps: [
      "Ingest pipeline job status or log",
      "Check freshness SLA compliance",
      "Detect schema drift against expected definition",
      "Assess data quality metrics (completeness, accuracy)",
      "Generate pipeline health report",
      "Recommend remediation or backfill",
      "Notify data pipeline owner",
    ],
    workspaceModules: [
      "Pipeline job selector",
      "Freshness SLA panel",
      "Schema drift detector",
      "Data quality scorecard",
      "Pipeline health report",
      "Remediation backlog",
    ],
    coreTools: [
      "freshness_checker",
      "schema_drift_detector",
      "data_quality_scorer",
      "health_report_generator",
      "remediation_planner",
    ],
    primaryActions: [
      "Check data freshness",
      "Detect schema drift",
      "Score data quality",
      "Generate health report",
      "Recommend remediation",
      "Notify pipeline owner",
    ],
    mockRunBehaviors: [
      "Check freshness: compares mock job timestamp against SLA threshold",
      "Detect drift: diffs mock schema against expected schema definition",
      "Score quality: computes completeness, null rate, duplicate rate metrics",
      "Generate report: produces structured pipeline health report",
      "Recommend remediation: proposes backfill, schema update, or pause",
      "Notify owner: drafts notification with issue summary (not sent)",
    ],
    requiredInputs: [
      "Pipeline job status/log",
      "Expected schema definition",
      "Quality check results",
      "Freshness SLA threshold",
    ],
    demoDataNeeded: [
      "job-status.json",
      "schema-definition.json",
      "quality-checks.json",
      "freshness-sla.json",
    ],
    resultPanels: [
      "Freshness SLA dashboard",
      "Schema drift diff view",
      "Data quality scorecard",
      "Pipeline health report",
    ],
    artifactTypes: ["report", "analysis", "recommendation", "checklist"],
    integrationTargets: ["dbt", "Airflow", "Prefect", "Dagster", "Fivetran", "Airbyte", "Great Expectations"],
    approvalGatedActions: [
      "Pause production pipeline",
      "Apply schema migration",
      "Execute data backfill",
      "Modify pipeline configuration",
    ],
    nonScopeLimits: [
      "No live pipeline connector",
      "No job execution control",
      "No schema migration execution",
      "No data backfill execution",
    ],
    evalCaseIds: ["datap-eval-001", "datap-eval-002", "datap-eval-003", "datap-eval-004", "datap-eval-005", "datap-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "field-service-operations-agent",
    name: "Field Service Operations Agent",
    category: "business-ops",
    templateFamily: "operations_dispatch",
    researchSources: ["repo_spec_only"],
    primaryWorkflowObject: "work_order",
    workflowSteps: [
      "Ingest work order or service request",
      "Assess job type, skill requirements, and SLA",
      "Match to available technician with skills and location",
      "Optimize route and schedule across work orders",
      "Generate dispatch plan and technician brief",
      "Track job status and SLA compliance",
      "Generate operations summary",
    ],
    workspaceModules: [
      "Work order intake panel",
      "Technician availability grid",
      "Skills/zone matching panel",
      "Route optimizer",
      "Dispatch plan panel",
      "Job status tracker",
      "Operations summary",
    ],
    coreTools: [
      "work_order_classifier",
      "technician_matcher",
      "route_optimizer",
      "sla_tracker",
      "dispatch_plan_generator",
      "operations_reporter",
    ],
    primaryActions: [
      "Classify work order",
      "Match technician to job",
      "Optimize route and schedule",
      "Generate dispatch plan",
      "Track job status",
      "Create operations summary",
    ],
    mockRunBehaviors: [
      "Classify order: assigns work type, skill requirements, SLA priority",
      "Match technician: selects best-fit technicians from mock availability/skills",
      "Optimize route: computes efficient route across mock locations",
      "Generate plan: produces structured dispatch plan with assignments",
      "Track status: updates mock job states, flags SLA-at-risk",
      "Create summary: generates operations report with metrics",
    ],
    requiredInputs: [
      "Work order details",
      "Technician availability data",
      "Skill requirements",
      "Service location(s)",
    ],
    demoDataNeeded: [
      "work-orders.json",
      "technician-availability.json",
      "skill-matrix.json",
      "location-data.json",
      "sla-policies.json",
    ],
    resultPanels: [
      "Technician matching panel",
      "Route map/plan",
      "Dispatch schedule",
      "Operations summary",
    ],
    artifactTypes: ["report", "checklist", "plan", "analysis"],
    integrationTargets: ["ServiceMax", "IFS Field Service", "Oracle Field Service", "Salesforce Field Service"],
    approvalGatedActions: [
      "Dispatch technician (real)",
      "Modify active work order",
      "Override SLA policy",
    ],
    nonScopeLimits: [
      "No live field service connector",
      "No actual dispatch execution",
      "No technician notification",
      "No route navigation",
    ],
    evalCaseIds: ["fso-eval-001", "fso-eval-002", "fso-eval-003", "fso-eval-004", "fso-eval-005", "fso-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "hr-people-ops-agent",
    name: "HR People Ops Agent",
    category: "hr",
    templateFamily: "intake_workflow",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "employee_event",
    workflowSteps: [
      "Intake employee lifecycle event (onboarding, offboarding, LOA)",
      "Validate eligibility and policy compliance",
      "Generate required documentation and checklists",
      "Coordinate cross-department tasks (IT, facilities, payroll)",
      "Route through approvals (manager, HRBP, legal)",
      "Track task completion across stakeholders",
      "Generate employee record update proposal",
    ],
    workspaceModules: [
      "Employee event intake",
      "Policy compliance checker",
      "Documentation generator",
      "Cross-department task tracker",
      "Approval workflow panel",
      "Employee record update panel",
    ],
    coreTools: [
      "event_validator",
      "policy_checker",
      "doc_generator",
      "task_coordinator",
      "approval_router",
      "record_updater",
    ],
    primaryActions: [
      "Process lifecycle event",
      "Check policy compliance",
      "Generate documentation",
      "Coordinate tasks across departments",
      "Submit for approval",
      "Generate record update",
    ],
    mockRunBehaviors: [
      "Process event: classifies event type, triggers appropriate workflow",
      "Check compliance: validates against mock HR policies and regulations",
      "Generate docs: produces offer letter, offboarding checklist, LOA notice",
      "Coordinate tasks: creates mock task assignments for IT/facilities/payroll",
      "Submit approval: routes for mock manager/HRBP approval",
      "Generate update: proposes HRIS record changes (not executed)",
    ],
    requiredInputs: [
      "Employee event type and details",
      "Employee record data",
      "Department policy references",
      "Approval chain definition",
    ],
    demoDataNeeded: [
      "employee-records.json",
      "hr-policies.json",
      "event-templates.json",
      "department-task-maps.json",
      "approval-chains.json",
    ],
    resultPanels: [
      "Employee event detail panel",
      "Policy compliance checklist",
      "Documentation panel",
      "Task tracker panel",
    ],
    artifactTypes: ["report", "checklist", "draft", "plan"],
    integrationTargets: ["Workday", "BambooHR", "Rippling", "Gusto", "HiBob", "ADP"],
    approvalGatedActions: [
      "Update employee record in HRIS",
      "Send documentation to employee",
      "Execute payroll change",
      "Grant system access",
    ],
    nonScopeLimits: [
      "No live HRIS connector",
      "No employee record mutation",
      "No payroll execution",
      "No system provisioning",
    ],
    evalCaseIds: ["hr-eval-001", "hr-eval-002", "hr-eval-003", "hr-eval-004", "hr-eval-005", "hr-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "identity-access-review-agent",
    name: "Identity & Access Review Agent",
    category: "security",
    templateFamily: "compliance_screening",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "access_certification",
    workflowSteps: [
      "Intake access review campaign definition",
      "Aggregate user entitlements and access across systems",
      "Identify high-risk access combinations (SoD violations)",
      "Detect stale accounts and excessive privileges",
      "Generate entitlement review packet per reviewer",
      "Route certification decisions for approval",
      "Produce remediation plan for revoked/changed access",
    ],
    workspaceModules: [
      "Campaign definition panel",
      "Entitlement aggregation grid",
      "SoD/risk violation panel",
      "Stale access detector",
      "Review packet generator",
      "Remediation plan panel",
    ],
    coreTools: [
      "entitlement_aggregator",
      "sod_violation_detector",
      "stale_access_finder",
      "risk_scorer",
      "review_packet_generator",
      "remediation_planner",
    ],
    primaryActions: [
      "Define access review campaign",
      "Aggregate user entitlements",
      "Detect SoD violations",
      "Find stale accounts",
      "Generate review packets",
      "Create remediation plan",
    ],
    mockRunBehaviors: [
      "Define campaign: sets scope, duration, reviewers from mock config",
      "Aggregate entitlements: collects mock user/role/privilege data across systems",
      "Detect SoD: flags conflicting access (e.g., create PO + approve PO)",
      "Find stale: identifies accounts with no login in 90+ days",
      "Generate packets: creates per-reviewer certification packets with evidence",
      "Create plan: drafts remediation steps for identified issues",
    ],
    requiredInputs: [
      "User/role/entitlement data",
      "SOD policy rules",
      "Access review scope",
      "Reviewer assignments",
    ],
    demoDataNeeded: [
      "user-entitlements.json",
      "role-definitions.json",
      "sod-policy-rules.json",
      "access-review-config.json",
      "reviewer-assignments.json",
    ],
    resultPanels: [
      "Entitlement overview panel",
      "SoD violation grid",
      "Stale access report",
      "Review packet preview",
    ],
    artifactTypes: ["report", "risk_matrix", "checklist", "approval_packet"],
    integrationTargets: ["SailPoint", "Okta IGA", "Saviynt", "Azure AD IGA", "One Identity"],
    approvalGatedActions: [
      "Revoke user access",
      "Modify role assignment",
      "Execute SoD remediation",
    ],
    nonScopeLimits: [
      "No live IGA connector",
      "No access modification",
      "No role/entitlement changes",
      "No account deprovisioning",
    ],
    evalCaseIds: ["iar-eval-001", "iar-eval-002", "iar-eval-003", "iar-eval-004", "iar-eval-005", "iar-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "iot-fleet-monitoring-agent",
    name: "IoT Fleet Monitoring Agent",
    category: "infrastructure",
    templateFamily: "monitoring_dashboard",
    researchSources: ["repo_spec_only"],
    primaryWorkflowObject: "device_fleet",
    workflowSteps: [
      "Ingest fleet telemetry data",
      "Classify device health status per unit",
      "Prioritize maintenance by criticality",
      "Detect predictive failure patterns",
      "Generate fleet health and maintenance report",
      "Recommend dispatch or maintenance actions",
    ],
    workspaceModules: [
      "Fleet overview dashboard",
      "Device health status grid",
      "Maintenance priority queue",
      "Predictive failure panel",
      "Telemetry trend charts",
      "Operations brief",
    ],
    coreTools: [
      "device_health_classifier",
      "maintenance_prioritizer",
      "predictive_failure_detector",
      "fleet_health_reporter",
      "dispatch_recommender",
    ],
    primaryActions: [
      "Classify device health",
      "Prioritize maintenance",
      "Detect predictive failures",
      "Generate fleet health report",
      "Recommend technician dispatch",
      "Adjust monitoring thresholds",
    ],
    mockRunBehaviors: [
      "Classify health: scores mock device telemetry against health thresholds",
      "Prioritize maintenance: ranks devices by criticality and health score",
      "Detect failures: identifies trend patterns suggesting imminent failure",
      "Generate report: produces structured fleet health report artifact",
      "Recommend dispatch: proposes technician dispatch with priority (not executed)",
      "Adjust thresholds: drafts new threshold values with rationale (not applied)",
    ],
    requiredInputs: [
      "Device telemetry data (CSV/JSON)",
      "Device metadata (location, type, install date)",
      "Health status thresholds",
      "Alert history (optional)",
    ],
    demoDataNeeded: [
      "device-telemetry.json",
      "device-metadata.json",
      "alert-history.json",
      "thresholds.json",
    ],
    resultPanels: [
      "Fleet health dashboard",
      "Device health grid",
      "Predictive failure alerts",
      "Maintenance queue",
    ],
    artifactTypes: ["report", "checklist", "recommendation", "analysis"],
    integrationTargets: ["AWS IoT Core", "Azure IoT Hub", "Google Cloud IoT", "Particle", "Balena", "Uptake"],
    approvalGatedActions: [
      "Dispatch technician",
      "Modify maintenance schedule",
      "Adjust production thresholds",
      "Send device command",
    ],
    nonScopeLimits: [
      "No live IoT connector",
      "No technician dispatch execution",
      "No device command execution",
      "No real-time telemetry streaming",
    ],
    evalCaseIds: ["iot-eval-001", "iot-eval-002", "iot-eval-003", "iot-eval-004", "iot-eval-005", "iot-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "log-management-agent",
    name: "Log Management Agent",
    category: "data",
    templateFamily: "analysis_report",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "log_query",
    workflowSteps: [
      "Intake log query or paste log content",
      "Parse and index log entries",
      "Cluster error patterns and frequency",
      "Detect anomalies against baseline",
      "Correlate events across timeframe",
      "Generate log investigation brief",
      "Recommend next steps",
    ],
    workspaceModules: [
      "Log intake/search panel",
      "Pattern cluster view",
      "Anomaly timeline",
      "Error/frequency histogram",
      "Log investigation brief",
      "Recommendations panel",
    ],
    coreTools: [
      "log_parser",
      "pattern_clusterer",
      "anomaly_detector",
      "correlation_engine",
      "investigation_brief_writer",
    ],
    primaryActions: [
      "Parse and analyze logs",
      "Cluster error patterns",
      "Detect anomalies",
      "Correlate events",
      "Generate investigation brief",
      "Save query for reference",
    ],
    mockRunBehaviors: [
      "Parse logs: ingests mock log lines, parses timestamps, levels, messages",
      "Cluster patterns: groups similar errors into named patterns with counts",
      "Detect anomalies: identifies log rate spikes vs mock baseline",
      "Correlate events: links related log entries across services",
      "Generate brief: produces structured investigation brief with evidence",
      "Save query: stores query configuration (local/UI only)",
    ],
    requiredInputs: [
      "Log content (paste or upload)",
      "Search filter/query (optional)",
      "Time range (optional)",
      "Service name (optional)",
    ],
    demoDataNeeded: [
      "error-logs.txt",
      "mixed-logs.txt",
      "anomaly-spike.log",
      "clean-logs.txt",
    ],
    resultPanels: [
      "Pattern cluster view",
      "Anomaly timeline chart",
      "Error frequency histogram",
      "Investigation brief",
    ],
    artifactTypes: ["report", "analysis", "summary", "evidence_packet"],
    integrationTargets: ["Splunk", "Elasticsearch", "Loki", "Datadog Logs", "CloudWatch Logs", "Sumo Logic"],
    approvalGatedActions: [
      "Notify service owner",
      "Attach log sample to incident ticket",
      "Modify log retention policy",
    ],
    nonScopeLimits: [
      "No live log source connector",
      "No real-time log streaming",
      "No alert creation",
      "No log retention changes",
    ],
    evalCaseIds: ["lm-eval-001", "lm-eval-002", "lm-eval-003", "lm-eval-004", "lm-eval-005", "lm-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "marketing-campaign-agent",
    name: "Marketing Campaign Agent",
    category: "business-ops",
    templateFamily: "campaign_planner",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "campaign_brief",
    workflowSteps: [
      "Define campaign objective and target audience",
      "Build audience segment from mock customer data",
      "Generate campaign brief with strategy and goals",
      "Draft channel-specific copy (email, social, SMS, push)",
      "Review brand and compliance guidelines",
      "Route for stakeholder approval",
      "Generate campaign performance projection",
    ],
    workspaceModules: [
      "Campaign brief composer",
      "Audience segment builder",
      "Channel copy generator",
      "Brand compliance checker",
      "Approval review panel",
      "Performance projection panel",
    ],
    coreTools: [
      "audience_segment_builder",
      "campaign_brief_writer",
      "copy_generator",
      "brand_checker",
      "compliance_checker",
      "approval_router",
    ],
    primaryActions: [
      "Build audience segment",
      "Generate campaign brief",
      "Draft channel copy",
      "Check brand compliance",
      "Submit for approval",
      "View performance projections",
    ],
    mockRunBehaviors: [
      "Build segment: queries mock customer data, creates audience with criteria",
      "Campaign brief: generates structured brief with objective, audience, strategy",
      "Draft copy: creates per-channel copy variants (email, social, SMS)",
      "Check brand: validates against mock brand/tone/voice guidelines",
      "Submit approval: routes campaign package for mock stakeholder review",
      "Projections: estimates mock reach, open rate, conversion from demo data",
    ],
    requiredInputs: [
      "Campaign objective and goals",
      "Target audience criteria",
      "Product/offer details",
      "Channel selection",
    ],
    demoDataNeeded: [
      "customer-data.json",
      "campaign-templates.json",
      "brand-guidelines.json",
      "channel-performance-benchmarks.json",
      "campaign-calendar.json",
    ],
    resultPanels: [
      "Audience segment summary",
      "Campaign brief preview",
      "Channel copy previews",
      "Approval status panel",
    ],
    artifactTypes: ["report", "draft", "plan", "approval_packet"],
    integrationTargets: ["Salesforce Marketing Cloud", "HubSpot Marketing", "Klaviyo", "Braze", "Mailchimp", "Marketo"],
    approvalGatedActions: [
      "Launch campaign to real audience",
      "Send campaign messages",
      "Modify brand guidelines",
    ],
    nonScopeLimits: [
      "No live marketing platform connector",
      "No campaign execution",
      "No message delivery",
      "No real-time performance data",
    ],
    evalCaseIds: ["mc-eval-001", "mc-eval-002", "mc-eval-003", "mc-eval-004", "mc-eval-005", "mc-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "observability-incident-agent",
    name: "Observability Incident Agent",
    category: "infrastructure",
    templateFamily: "incident_response",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "monitoring_alert",
    workflowSteps: [
      "Ingest monitoring alert with payload",
      "Correlate traces, logs, and metrics for context",
      "Identify suspected root cause",
      "Retrieve relevant runbook",
      "Assess blast radius and severity",
      "Generate incident brief and timeline",
      "Propose escalation or mitigation actions",
    ],
    workspaceModules: [
      "Alert correlation timeline",
      "Trace/log/metric cross-reference",
      "Suspected root cause panel",
      "Runbook reference panel",
      "Incident brief",
      "Escalation recommendations",
    ],
    coreTools: [
      "alert_correlator",
      "root_cause_analyzer",
      "runbook_matcher",
      "blast_radius_calculator",
      "incident_brief_writer",
    ],
    primaryActions: [
      "Correlate alert with telemetry",
      "Analyze root cause",
      "Relevant runbook",
      "Assess blast radius",
      "Generate incident brief",
      "Propose escalation",
    ],
    mockRunBehaviors: [
      "Correlate alert: links alert to mock traces, logs, metrics",
      "Root cause: identifies likely cause from mock telemetry patterns",
      "Runbook: matches incident type to mock runbook library entry",
      "Blast radius: estimates affected services/users from mock topology",
      "Generate brief: produces structured incident brief with timeline",
      "Propose escalation: recommends on-call page, severity upgrade (not executed)",
    ],
    requiredInputs: [
      "Monitoring alert payload",
      "Log/trace sample (optional)",
      "Metric snapshot (optional)",
    ],
    demoDataNeeded: [
      "alert-payload.json",
      "log-sample.txt",
      "trace-sample.json",
      "metric-snapshot.json",
    ],
    resultPanels: [
      "Alert correlation timeline",
      "Root cause analysis panel",
      "Runbook reference panel",
      "Incident brief",
    ],
    artifactTypes: ["report", "analysis", "recommendation", "evidence_packet"],
    integrationTargets: ["Datadog", "New Relic", "Grafana", "PagerDuty", "Opsgenie", "Splunk", "Honeycomb"],
    approvalGatedActions: [
      "Page on-call engineer",
      "Create incident ticket in production",
      "Trigger mitigation action",
    ],
    nonScopeLimits: [
      "No live monitoring connector",
      "No alert creation/modification",
      "No paging execution",
      "No incident auto-resolution",
    ],
    evalCaseIds: ["oi-eval-001", "oi-eval-002", "oi-eval-003", "oi-eval-004", "oi-eval-005", "oi-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "ai-agent-orchestration-agent",
    name: "AI Agent Orchestration Agent",
    category: "ai-platform",
    templateFamily: "orchestration",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "user_goal",
    workflowSteps: [
      "Intake user goal description",
      "Decompose goal into sub-tasks",
      "Select appropriate agent(s) for each sub-task",
      "Build dependency graph with execution order",
      "Estimate timeline and resource needs",
      "Flag required approvals",
      "Generate orchestration plan artifact",
    ],
    workspaceModules: [
      "Goal composer",
      "Task decomposition panel",
      "Agent selection panel",
      "Dependency graph viewer",
      "Approval flag panel",
      "Orchestration plan",
    ],
    coreTools: [
      "goal_decomposer",
      "agent_selector",
      "dependency_graph_builder",
      "approval_risk_mapper",
      "plan_generator",
    ],
    primaryActions: [
      "Decompose user goal",
      "Select matching agents",
      "Build dependency graph",
      "Estimate timeline",
      "Flag approval requirements",
      "Generate orchestration plan",
    ],
    mockRunBehaviors: [
      "Decompose goal: breaks user goal into mock sub-tasks with dependencies",
      "Select agents: matches sub-tasks to canonical agent slugs by capability",
      "Build graph: creates directed acyclic graph of execution order",
      "Estimate timeline: computes mock duration per task with parallelism",
      "Flag approvals: marks tasks requiring human approval based on risk",
      "Generate plan: produces structured orchestration plan artifact",
    ],
    requiredInputs: [
      "User goal description",
      "Constraints (budget, time, max agents)",
      "Priority/urgency context",
    ],
    demoDataNeeded: [
      "goal-templates.json",
      "agent-capability-matrix.json",
      "dependency-patterns.json",
      "churn-analysis-goal.json",
      "conflicting-constraints.json",
      "unknown-agent-request.json",
    ],
    resultPanels: [
      "Task decomposition tree",
      "Agent selection matrix",
      "Dependency graph",
      "Orchestration plan",
    ],
    artifactTypes: ["plan", "risk_matrix", "report", "analysis"],
    integrationTargets: ["LangGraph", "CrewAI", "AutoGen", "OpenAI Swarm"],
    approvalGatedActions: [
      "Dispatch sub-agent run",
      "Execute write-action through sub-agent",
    ],
    nonScopeLimits: [
      "No live multi-agent dispatch",
      "No real connector execution",
      "No runtime orchestration engine",
      "No agent-to-agent messaging",
    ],
    evalCaseIds: ["aio-eval-001", "aio-eval-002", "aio-eval-003", "aio-eval-004", "aio-eval-005", "aio-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "ai-model-gateway-agent",
    name: "AI Model Gateway Agent",
    category: "ai-platform",
    templateFamily: "monitoring_dashboard",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "model_route",
    workflowSteps: [
      "View model routing configuration",
      "Analyze cost, latency, and token usage per model",
      "Compare model performance on key metrics",
      "Detect rate limits and quota issues",
      "Audit model access and governance",
      "Generate model routing recommendation",
      "Propose guardrail and safety configuration",
    ],
    workspaceModules: [
      "Model routing dashboard",
      "Cost/latency analyzer",
      "Performance comparison panel",
      "Quota/rate limit tracker",
      "Audit/compliance panel",
      "Guardrail configurator",
    ],
    coreTools: [
      "cost_analyzer",
      "latency_monitor",
      "model_comparator",
      "quota_tracker",
      "audit_checker",
      "guardrail_configurator",
    ],
    primaryActions: [
      "View routing configuration",
      "Analyze cost and latency",
      "Compare model performance",
      "Check rate limits",
      "Audit model access",
      "Recommend routing changes",
    ],
    mockRunBehaviors: [
      "View routing: displays mock routing rules with model weights",
      "Analyze cost: computes mock cost per 1K tokens, latency percentiles",
      "Compare models: ranks models by mock cost/quality/speed metrics",
      "Check limits: shows mock quota usage and remaining capacity",
      "Audit access: validates mock API key permissions and governance",
      "Recommend: proposes routing changes based on mock analysis",
    ],
    requiredInputs: [
      "Model routing configuration",
      "Usage/cost data",
      "Performance metrics",
      "Governance policy",
    ],
    demoDataNeeded: [
      "routing-config.json",
      "usage-cost-data.json",
      "model-benchmarks.json",
      "guardrail-policies.json",
      "audit-log.json",
    ],
    resultPanels: [
      "Model routing overview",
      "Cost analysis panel",
      "Performance comparison chart",
      "Audit/compliance panel",
    ],
    artifactTypes: ["report", "analysis", "recommendation", "risk_matrix"],
    integrationTargets: ["Portkey", "LiteLLM", "Helicone", "OpenRouter", "LangSmith"],
    approvalGatedActions: [
      "Modify production routing rules",
      "Add new model provider",
      "Change guardrail configuration",
    ],
    nonScopeLimits: [
      "No live model gateway connector",
      "No routing rule modification",
      "No provider integration",
      "No guardrail enforcement",
    ],
    evalCaseIds: ["amg-eval-001", "amg-eval-002", "amg-eval-003", "amg-eval-004", "amg-eval-005", "amg-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "api-security-agent",
    name: "API Security Agent",
    category: "security",
    templateFamily: "risk_investigation",
    researchSources: ["Part 2", "repo_spec_only"],
    primaryWorkflowObject: "api_security_alert",
    workflowSteps: [
      "Ingest API security alert or audit finding",
      "Classify vulnerability type (OWASP API Top 10)",
      "Assess impact scope and data sensitivity",
      "Generate evidence packet with findings",
      "Propose remediation plan with priority",
      "Route for security review",
      "Track remediation status",
    ],
    workspaceModules: [
      "API security alert intake",
      "Vulnerability classification panel",
      "Impact assessment panel",
      "Evidence packet viewer",
      "Remediation plan panel",
      "Security review queue",
    ],
    coreTools: [
      "vulnerability_classifier",
      "impact_scorer",
      "evidence_collector",
      "remediation_planner",
      "security_review_router",
    ],
    primaryActions: [
      "Classify API vulnerability",
      "Assess impact scope",
      "Collect evidence",
      "Create remediation plan",
      "Route for security review",
      "Track remediation status",
    ],
    mockRunBehaviors: [
      "Classify: maps mock finding to OWASP API Top 10 category",
      "Assess impact: computes mock data sensitivity and blast radius",
      "Collect evidence: aggregates mock request/response logs, config snippets",
      "Create plan: drafts prioritized remediation steps with timeline",
      "Route review: assigns to mock security reviewer with context",
      "Track status: updates mock remediation progress with notes",
    ],
    requiredInputs: [
      "API security alert/finding",
      "API specification/contract",
      "Threat assessment (optional)",
      "Data classification tags",
    ],
    demoDataNeeded: [
      "api-vulnerabilities.json",
      "owasp-top10-rules.json",
      "api-spec-sample.json",
      "remediation-playbooks.json",
      "security-review-queue.json",
    ],
    resultPanels: [
      "Vulnerability classification panel",
      "Impact assessment chart",
      "Evidence packet viewer",
      "Remediation tracker",
    ],
    artifactTypes: ["report", "evidence_packet", "recommendation", "risk_matrix"],
    integrationTargets: ["Salt Security", "Noname Security", "Traceable", "42Crunch", "OWASP ZAP"],
    approvalGatedActions: [
      "Apply WAF rule modification",
      "Block API endpoint",
      "Modify API authentication policy",
    ],
    nonScopeLimits: [
      "No live API security scanner",
      "No WAF configuration changes",
      "No endpoint blocking",
      "No authentication policy changes",
    ],
    evalCaseIds: ["apis-eval-001", "apis-eval-002", "apis-eval-003", "apis-eval-004", "apis-eval-005", "apis-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "compliance-screening-agent",
    name: "Compliance Screening Agent",
    category: "security",
    templateFamily: "compliance_screening",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "screening_case",
    workflowSteps: [
      "Intake entity for screening (customer, vendor, employee)",
      "Run against sanctions, KYC/AML, and PEP watchlists",
      "Score match confidence and risk level",
      "Summarize potential matches with evidence",
      "Generate case packet for compliance review",
      "Recommend disposition (clear/escalate/investigate)",
      "Record screening decision and rationale",
    ],
    workspaceModules: [
      "Screening intake panel",
      "Watchlist match results",
      "Risk scoring panel",
      "Evidence summary panel",
      "Case packet composer",
      "Disposition panel",
      "Audit record panel",
    ],
    coreTools: [
      "watchlist_matcher",
      "risk_scorer",
      "evidence_summarizer",
      "case_packet_generator",
      "disposition_recommender",
      "audit_logger",
    ],
    primaryActions: [
      "Screen entity against watchlists",
      "Score match risk",
      "Summarize match evidence",
      "Generate case packet",
      "Recommend disposition",
      "Record audit trail",
    ],
    mockRunBehaviors: [
      "Screen entity: runs mock entity name against mock sanctions/PEP/KYC lists",
      "Score risk: assigns risk level (low/medium/high) from match quality",
      "Summarize evidence: compiles matching entries with confidence scores",
      "Generate packet: creates structured compliance case packet artifact",
      "Recommend: proposes clear/escalate/investigate based on risk score",
      "Record audit: logs screening decision and rationale (mock/UI only)",
    ],
    requiredInputs: [
      "Entity name and identifiers",
      "Entity type (customer/vendor/employee)",
      "Jurisdiction/region",
      "Screening scope (sanctions, PEP, adverse media)",
    ],
    demoDataNeeded: [
      "sanctions-list-mock.json",
      "pep-list-mock.json",
      "kyc-aml-rules.json",
      "entity-profiles.json",
      "screening-history.json",
    ],
    resultPanels: [
      "Match results panel",
      "Risk score dashboard",
      "Evidence summary panel",
      "Case packet preview",
    ],
    artifactTypes: ["report", "evidence_packet", "recommendation", "risk_matrix"],
    integrationTargets: ["ComplyAdvantage", "WorldCheck", "LexisNexis", "Dow Jones Risk", "Refinitiv World-Check"],
    approvalGatedActions: [
      "Finalize screening disposition",
      "Clear entity for business",
      "File suspicious activity report",
    ],
    nonScopeLimits: [
      "No live sanctions/PEP datastores",
      "No regulatory filing",
      "No actual screening execution on real entities",
      "No adverse media API integration",
    ],
    evalCaseIds: ["comp-eval-001", "comp-eval-002", "comp-eval-003", "comp-eval-004", "comp-eval-005", "comp-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "financial-reconciliation-agent",
    name: "Financial Reconciliation Agent",
    category: "finance",
    templateFamily: "reconciliation_close",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "reconciliation_batch",
    workflowSteps: [
      "Load transaction data from source systems",
      "Match transactions across accounts and ledgers",
      "Detect exceptions and unmatched items",
      "Explain variance with root cause analysis",
      "Generate close-ready evidence packet",
      "Propose adjusting entries",
      "Create reconciliation certification",
    ],
    workspaceModules: [
      "Transaction loader",
      "Match engine panel",
      "Exception detector",
      "Variance explainer",
      "Evidence packet composer",
      "Adjusting entry proposer",
      "Certification panel",
    ],
    coreTools: [
      "transaction_matcher",
      "exception_detector",
      "variance_analyzer",
      "evidence_packet_builder",
      "certification_generator",
    ],
    primaryActions: [
      "Load transaction data",
      "Match transactions",
      "Detect exceptions",
      "Explain variance",
      "Generate close packet",
      "Propose adjusting entry",
    ],
    mockRunBehaviors: [
      "Load data: ingests mock GL and subledger transaction fixtures",
      "Match transactions: pairs mock entries by amount, date, reference",
      "Detect exceptions: flags unmatched amounts, timing differences, rounding",
      "Explain variance: generates natural language explanation for each exception",
      "Generate packet: produces structured close-ready evidence packet artifact",
      "Propose entry: drafts adjusting journal entry with rationale (not posted)",
    ],
    requiredInputs: [
      "Transaction source data (GL, subledger)",
      "Reconciliation rules/policies",
      "Tolerance thresholds",
      "Period/close date",
    ],
    demoDataNeeded: [
      "gl-transactions.json",
      "subledger-transactions.json",
      "reconciliation-rules.json",
      "historical-close-data.json",
      "tolerance-thresholds.json",
    ],
    resultPanels: [
      "Transaction match grid",
      "Exception list panel",
      "Variance explanation panel",
      "Close packet preview",
    ],
    artifactTypes: ["report", "evidence_packet", "recommendation", "analysis"],
    integrationTargets: ["BlackLine", "Ledge", "FloQast", "Trintech", "Oracle ARCS", "SAP Intercompany"],
    approvalGatedActions: [
      "Post adjusting journal entry",
      "Certify reconciliation as complete",
      "Close period in ERP",
    ],
    nonScopeLimits: [
      "No live ERP connector",
      "No journal entry posting",
      "No period close execution",
      "No balance certification",
    ],
    evalCaseIds: ["fr-eval-001", "fr-eval-002", "fr-eval-003", "fr-eval-004", "fr-eval-005", "fr-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "fraud-detection-agent",
    name: "Fraud Detection Agent",
    category: "security",
    templateFamily: "risk_investigation",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "transaction_alert",
    workflowSteps: [
      "Ingest transaction or activity alert",
      "Score risk based on behavioral patterns and rules",
      "Correlate with historical fraud signals",
      "Generate risk rationale with evidence markers",
      "Prioritize case for investigation",
      "Recommend action (monitor/escalate/block)",
      "Generate fraud case packet for review",
    ],
    workspaceModules: [
      "Alert intake panel",
      "Risk scoring engine",
      "Behavioral pattern analyzer",
      "Evidence correlation panel",
      "Case prioritization queue",
      "Case packet composer",
      "Action recommendation panel",
    ],
    coreTools: [
      "risk_scorer",
      "behavioral_analyzer",
      "fraud_signal_correlator",
      "case_prioritizer",
      "case_packet_generator",
      "action_recommender",
    ],
    primaryActions: [
      "Score transaction risk",
      "Analyze behavioral patterns",
      "Correlate fraud signals",
      "Prioritize case for review",
      "Generate case packet",
      "Recommend action",
    ],
    mockRunBehaviors: [
      "Score risk: computes mock risk score from transaction amount, velocity, geo",
      "Analyze patterns: detects deviation from mock normal user behavior",
      "Correlate signals: links alert to mock known fraud indicators",
      "Prioritize case: ranks by risk score, amount, and pattern severity",
      "Generate packet: produces structured fraud case packet with evidence",
      "Recommend action: proposes monitor/escalate/block (block requires approval)",
    ],
    requiredInputs: [
      "Transaction/activity data",
      "Risk rules configuration",
      "Historical fraud data (optional)",
      "Entity profile/transaction history",
    ],
    demoDataNeeded: [
      "transaction-alerts.json",
      "risk-rules.json",
      "fraud-patterns.json",
      "entity-profiles.json",
      "investigation-queue.json",
    ],
    resultPanels: [
      "Risk score chart",
      "Behavioral analysis panel",
      "Fraud signal correlation",
      "Case packet preview",
    ],
    artifactTypes: ["report", "evidence_packet", "risk_matrix", "recommendation"],
    integrationTargets: ["Feedzai", "Sift", "Forter", "Kount", "Signifyd", "SEON"],
    approvalGatedActions: [
      "Block transaction/account",
      "File suspicious activity report",
      "Escalate to law enforcement",
    ],
    nonScopeLimits: [
      "No live fraud detection connector",
      "No transaction blocking",
      "No regulatory filing",
      "No real-time transaction monitoring",
    ],
    evalCaseIds: ["fd-eval-001", "fd-eval-002", "fd-eval-003", "fd-eval-004", "fd-eval-005", "fd-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "security-incident-agent",
    name: "Security Incident Agent",
    category: "security",
    templateFamily: "incident_response",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "security_alert",
    workflowSteps: [
      "Ingest security alert (phishing, impersonation, app fraud)",
      "Classify incident type and severity",
      "Gather evidence (alert, asset, identity, timeline)",
      "Build incident timeline with correlated events",
      "Assess severity and impact",
      "Generate triage packet",
      "Propose containment and escalation actions",
    ],
    workspaceModules: [
      "Alert intake",
      "Incident classification",
      "Evidence collection panel",
      "Incident timeline",
      "Severity assessment",
      "Triage packet",
      "Proposed actions panel",
    ],
    coreTools: [
      "incident_classifier",
      "evidence_collector",
      "timeline_builder",
      "severity_assessor",
      "triage_packet_generator",
    ],
    primaryActions: [
      "Classify incident type",
      "Collect evidence",
      "Build incident timeline",
      "Assess severity",
      "Generate triage packet",
      "Propose escalation or containment",
    ],
    mockRunBehaviors: [
      "Classify: maps mock alert to incident type and severity",
      "Collect evidence: aggregates mock screenshots, domain records, account data",
      "Build timeline: sequences mock events with timestamps and correlations",
      "Assess severity: assigns severity level with rationale",
      "Generate packet: produces structured triage packet artifact",
      "Propose containment: recommends isolation, escalation (not executed)",
    ],
    requiredInputs: [
      "Alert source and description",
      "Affected brand/asset",
      "Alert type (phishing, social media, app fraud)",
    ],
    demoDataNeeded: [
      "phishing-alerts.json",
      "social-impersonation.json",
      "app-fraud.json",
      "domain-registry-mock.json",
      "incident-templates.json",
    ],
    resultPanels: [
      "Incident classification panel",
      "Evidence collection panel",
      "Incident timeline view",
      "Triage packet preview",
    ],
    artifactTypes: ["report", "evidence_packet", "recommendation"],
    integrationTargets: ["ZeroFox", "Brandwatch", "Doppel", "CrowdStrike"],
    approvalGatedActions: [
      "Initiate takedown request",
      "Isolate compromised asset",
      "Block malicious domain/IP",
      "Notify external stakeholders",
    ],
    nonScopeLimits: [
      "No live SIEM/SOAR connector",
      "No automated takedown execution",
      "No domain registrar API integration",
      "No real-time threat intel feed",
    ],
    evalCaseIds: ["si-eval-001", "si-eval-002", "si-eval-003", "si-eval-004", "si-eval-005", "si-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "security-operations-agent",
    name: "Security Operations Agent",
    category: "security",
    templateFamily: "incident_response",
    researchSources: ["Part 3", "repo_spec_only"],
    primaryWorkflowObject: "soc_alert",
    workflowSteps: [
      "Ingest SIEM/SOAR alert",
      "Enrich with threat intelligence and context",
      "Investigate IoCs (IPs, domains, hashes, behaviors)",
      "Build incident timeline with attack chain mapping",
      "Classify incident verdict (true positive, false positive, benign)",
      "Generate SOC incident report",
      "Propose containment and response playbook",
    ],
    workspaceModules: [
      "SIEM alert intake",
      "Threat enrichment panel",
      "IoC investigation panel",
      "Attack chain mapper",
      "Incident verdict panel",
      "SOC incident report",
      "Playbook selector",
    ],
    coreTools: [
      "alert_enricher",
      "ioc_investigator",
      "attack_chain_mapper",
      "verdict_classifier",
      "soc_report_generator",
      "playbook_recommender",
    ],
    primaryActions: [
      "Enrich alert with threat intel",
      "Investigate IoCs",
      "Map attack chain",
      "Classify incident verdict",
      "Generate SOC report",
      "Recommend response playbook",
    ],
    mockRunBehaviors: [
      "Enrich alert: adds mock threat intel context (geo, reputation, TTPs)",
      "Investigate IoCs: queries mock threat intel for IP/domain/hash",
      "Map attack chain: builds MITRE ATT&CK-aligned mock kill chain",
      "Classify verdict: determines true positive/false positive with rationale",
      "Generate report: produces structured SOC incident report artifact",
      "Recommend playbook: selects mock response playbook based on incident type",
    ],
    requiredInputs: [
      "SIEM/SOAR alert payload",
      "IoC list (IPs, domains, hashes)",
      "Environment context",
      "Threat intel sources (optional)",
    ],
    demoDataNeeded: [
      "soc-alerts.json",
      "threat-intel-mock.json",
      "ioc-samples.json",
      "attack-patterns.json",
      "response-playbooks.json",
    ],
    resultPanels: [
      "Alert enrichment panel",
      "IoC investigation results",
      "Attack chain visualization",
      "SOC incident report",
    ],
    artifactTypes: ["report", "evidence_packet", "recommendation", "analysis"],
    integrationTargets: ["Splunk Enterprise Security", "Microsoft Sentinel", "CrowdStrike Falcon", "Palo Alto XSIAM"],
    approvalGatedActions: [
      "Contain endpoint/host",
      "Block IoC at firewall",
      "Isolate network segment",
      "Escalate to incident response team",
    ],
    nonScopeLimits: [
      "No live SIEM/SOAR connector",
      "No IoC blocking execution",
      "No endpoint containment",
      "No automated incident response",
    ],
    evalCaseIds: ["so-eval-001", "so-eval-002", "so-eval-003", "so-eval-004", "so-eval-005", "so-eval-006"],
    evalCaseCount: 6,
  },
  {
    slug: "supply-chain-security-agent",
    name: "Software Supply Chain Security Agent",
    category: "security",
    templateFamily: "risk_investigation",
    researchSources: ["Part 4", "repo_spec_only"],
    primaryWorkflowObject: "dependency_manifest",
    workflowSteps: [
      "Scan software dependency manifest (SBOM, lockfile)",
      "Classify dependency risk (known vulns, malicious, stale)",
      "Identify reachable and exploitable vulnerabilities",
      "Prioritize risks by severity and reachability",
      "Generate remediation plan with fix versions",
      "Draft remediation PR proposal",
      "Track remediation progress",
    ],
    workspaceModules: [
      "Manifest upload/scanner",
      "Dependency risk dashboard",
      "Vulnerability classification panel",
      "Reachability analyzer",
      "Remediation plan panel",
      "PR proposal panel",
      "Remediation tracker",
    ],
    coreTools: [
      "manifest_scanner",
      "dependency_risk_classifier",
      "reachability_analyzer",
      "vulnerability_prioritizer",
      "remediation_planner",
      "pr_proposal_generator",
    ],
    primaryActions: [
      "Scan dependency manifest",
      "Classify dependency risk",
      "Analyze reachability",
      "Prioritize vulnerabilities",
      "Generate remediation plan",
      "Draft remediation PR",
    ],
    mockRunBehaviors: [
      "Scan manifest: parses mock package.json/SBOM, identifies all dependencies",
      "Classify risk: assigns risk per dependency (malicious, vulnerable, stale)",
      "Analyze reachability: determines if vulnerable code is actually called",
      "Prioritize: ranks by CVSS score × reachability × fix availability",
      "Generate plan: produces prioritized remediation plan with fix versions",
      "Draft PR: creates mock PR proposal with dependency bumps and changelog",
    ],
    requiredInputs: [
      "Dependency manifest (package.json, lockfile, SBOM)",
      "Vulnerability database reference",
      "Project context and criticality",
      "Existing security policies",
    ],
    demoDataNeeded: [
      "package-manifest.json",
      "sbom-sample.json",
      "cve-database-mock.json",
      "reachability-report.json",
      "remediation-templates.json",
    ],
    resultPanels: [
      "Dependency risk dashboard",
      "Vulnerability classification grid",
      "Reachability analysis panel",
      "Remediation PR preview",
    ],
    artifactTypes: ["report", "risk_matrix", "recommendation", "plan"],
    integrationTargets: ["Socket", "Snyk", "Endor Labs", "Chainguard", "Dependabot", "OWASP Dependency Check"],
    approvalGatedActions: [
      "Create PR in production repo",
      "Bump dependency version in lockfile",
      "Block release based on dependency risk",
    ],
    nonScopeLimits: [
      "No live repo/registry connector",
      "No PR creation in production",
      "No dependency update execution",
      "No release pipeline blocking",
    ],
    evalCaseIds: ["scs-eval-001", "scs-eval-002", "scs-eval-003", "scs-eval-004", "scs-eval-005", "scs-eval-006"],
    evalCaseCount: 6,
  },
];

export function getWorkbenchRequirement(slug: string): WorkbenchRequirement | undefined {
  return WORKBENCH_REQUIREMENTS.find((r) => r.slug === slug);
}

export function listWorkbenchRequirements(): WorkbenchRequirement[] {
  return WORKBENCH_REQUIREMENTS;
}
