import type { MediaProviderModelEntry } from "./types";
import { getFalCatalogEndpoints } from "../fal-catalog";

export const PROVIDER_MODEL_ENTRIES: MediaProviderModelEntry[] = [
  // ── Mock — fully available ────────────────────────────────────────────────
  {
    providerId: "mock",
    modelId: "mock-image-default",
    displayName: "Mock Image Default",
    capability: "text-to-image",
    inputTypes: ["text"],
    outputTypes: ["image"],
    supportsAsync: false,
    supportsImage: true,
    supportsVideo: false,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: [],
    status: "mock",
  },
  {
    providerId: "mock",
    modelId: "mock-video-default",
    displayName: "Mock Video Default",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: false,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: [],
    status: "mock",
  },
  {
    providerId: "mock",
    modelId: "mock-voiceover-default",
    displayName: "Mock Voiceover Default",
    capability: "text-to-speech",
    inputTypes: ["text"],
    outputTypes: ["audio"],
    supportsAsync: false,
    supportsImage: false,
    supportsVideo: false,
    supportsAudio: true,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: [],
    status: "mock",
  },
  // ── Cortex — setup-required (API may be configured, adapter not implemented) ─
  {
    providerId: "cortex",
    modelId: "cortex-image-default",
    displayName: "Cortex Image Default",
    capability: "text-to-image",
    inputTypes: ["text"],
    outputTypes: ["image"],
    supportsAsync: true,
    supportsImage: true,
    supportsVideo: false,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["CORTEX_API_KEY"],
    status: "setup-required",
  },
  {
    providerId: "cortex",
    modelId: "cortex-video-default",
    displayName: "Cortex Video Default",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["CORTEX_API_KEY"],
    status: "setup-required",
  },
  {
    providerId: "cortex",
    modelId: "cortex-audio-default",
    displayName: "Cortex Audio Default",
    capability: "text-to-speech",
    inputTypes: ["text"],
    outputTypes: ["audio"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: false,
    supportsAudio: true,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["CORTEX_API_KEY"],
    status: "setup-required",
  },
  // ── OpenAI — setup-required only; no real image adapter in repo ────────────
  {
    providerId: "openai",
    // STU-P0-01: gpt-image-1 (dall-e-3 retired) — see openai-create-image-contract.ts.
    modelId: "gpt-image-1",
    displayName: "GPT Image 1",
    capability: "text-to-image",
    inputTypes: ["text"],
    outputTypes: ["image"],
    supportsAsync: false,
    supportsImage: true,
    supportsVideo: false,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["OPENAI_API_KEY"],
    status: "setup-required",
  },
  // ── Replicate — setup-required / planned ───────────────────────────────────
  {
    providerId: "replicate",
    modelId: "replicate-image-default",
    displayName: "Replicate Image Default",
    capability: "text-to-image",
    inputTypes: ["text"],
    outputTypes: ["image"],
    supportsAsync: true,
    supportsImage: true,
    supportsVideo: false,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["REPLICATE_API_TOKEN"],
    status: "setup-required",
  },
  {
    providerId: "replicate",
    modelId: "replicate-video-default",
    displayName: "Replicate Video Default",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["REPLICATE_API_TOKEN"],
    status: "setup-required",
  },
  // ── Fal — image-to-video only in this repo ────────────────────────────────
  {
    providerId: "fal",
    modelId: "fal-ai/wan-i2v",
    displayName: "fal · wan-i2v",
    capability: "image-to-video",
    inputTypes: ["text", "image"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["FAL_KEY"],
    status: "setup-required",
  },
  // ── ElevenLabs — setup-required / planned ──────────────────────────────────
  {
    providerId: "elevenlabs",
    modelId: "elevenlabs-tts",
    displayName: "ElevenLabs TTS",
    capability: "text-to-speech",
    inputTypes: ["text"],
    outputTypes: ["audio"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: false,
    supportsAudio: true,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["ELEVENLABS_API_KEY"],
    status: "setup-required",
  },
  {
    providerId: "elevenlabs",
    modelId: "elevenlabs-voice-design",
    displayName: "ElevenLabs Voice Design",
    capability: "voice-design",
    inputTypes: ["text", "audio"],
    outputTypes: ["audio"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: false,
    supportsAudio: true,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["ELEVENLABS_API_KEY"],
    status: "setup-required",
  },
  // ── Runway — setup-required / planned (generic video provider placeholder) ──
  {
    providerId: "runway",
    modelId: "runway-video-default",
    displayName: "Runway Video Default",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["RUNWAY_API_SECRET"],
    status: "setup-required",
  },
  // ── Generic video provider placeholder ────────────────────────────────────
  {
    providerId: "generic-video",
    modelId: "generic-video-default",
    displayName: "Generic Text-to-Video",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["GENERIC_VIDEO_API_URL", "GENERIC_VIDEO_API_KEY"],
    status: "setup-required",
  },
  // ── Kling — setup-required / planned ──────────────────────────────────────
  {
    providerId: "kling",
    modelId: "kling-video-default",
    displayName: "Kling Video Default",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["KLING_API_KEY"],
    status: "setup-required",
  },
  // ── Luma — setup-required / planned ───────────────────────────────────────
  {
    providerId: "luma",
    modelId: "luma-video-default",
    displayName: "Luma Video Default",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["LUMA_API_KEY"],
    status: "setup-required",
  },
  // ── Pika — setup-required / planned ───────────────────────────────────────
  {
    providerId: "pika",
    modelId: "pika-video-default",
    displayName: "Pika Video Default",
    capability: "text-to-video",
    inputTypes: ["text"],
    outputTypes: ["video"],
    supportsAsync: true,
    supportsImage: false,
    supportsVideo: true,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["PIKA_API_KEY"],
    status: "setup-required",
  },
  // ── Stability — setup-required / planned (Stability-style image placeholder) ─
  {
    providerId: "stability",
    modelId: "sd-xl",
    displayName: "Stable Diffusion XL",
    capability: "text-to-image",
    inputTypes: ["text"],
    outputTypes: ["image"],
    supportsAsync: false,
    supportsImage: true,
    supportsVideo: false,
    supportsAudio: false,
    supportsGameAssets: false,
    estimatedCost: "not provided",
    envRequired: ["STABILITY_API_KEY"],
    status: "setup-required",
  },
  // ── Custom provider placeholder ───────────────────────────────────────────
  {
    providerId: "custom",
    modelId: "custom-media-default",
    displayName: "Custom Media Default",
    capability: "text-to-image",
    inputTypes: ["text"],
    outputTypes: ["image"],
    supportsAsync: true,
    supportsImage: true,
    supportsVideo: true,
    supportsAudio: true,
    supportsGameAssets: true,
    estimatedCost: "not provided",
    envRequired: ["CUSTOM_MEDIA_API_KEY"],
    status: "planned",
  },
];

export function getProviderModelEntries(providerId: string): MediaProviderModelEntry[] {
  return PROVIDER_MODEL_ENTRIES.filter((e) => e.providerId === providerId);
}

export function getProviderModelEntry(providerId: string, modelId: string): MediaProviderModelEntry | undefined {
  return PROVIDER_MODEL_ENTRIES.find((e) => e.providerId === providerId && e.modelId === modelId);
}

// ─── Shared catalog bridge (J03) ─────────────────────────────────────────────
// Catalog-known fal endpoints stay setup-required with a factual posture:
// visible for browsing/routing decisions, never executable without a verified
// adapter. The production fal lane still constrains execution to qualified routes.
export function getFalCatalogProviderEntries(): MediaProviderModelEntry[] {
  return getFalCatalogEndpoints()
    .filter((endpoint) => endpoint.disposition !== "excluded")
    .map((endpoint) => ({
      providerId: "fal" as const,
      modelId: endpoint.endpointId,
      displayName: `fal · ${endpoint.endpointId}`,
      capability: endpoint.task,
      inputTypes: endpoint.task.includes("image-to") || endpoint.task.includes("image-") ? ["text", "image"] : ["text"],
      outputTypes: [endpoint.modality],
      supportsAsync: true,
      supportsImage: endpoint.modality === "image",
      supportsVideo: endpoint.modality === "video",
      supportsAudio: endpoint.modality === "audio",
      supportsGameAssets: false,
      estimatedCost: "not provided",
      envRequired: ["FAL_KEY"],
      status: "setup-required" as const,
    }));
}
