/**
 * packages/contracts/voice/provenance.ts
 *
 * VOI-13 — provenance records and export manifests.
 *
 * Provenance records capture the full audit chain of a voice output:
 * operation policy version, disclosure policy version + block, provider/
 * model/voice, input snapshot hash, output assets, and export manifest hash.
 */

export const VOICE_DISCLOSURE_POLICY_VERSION = "voice-disclosure-v1";

export const VOICE_DISCLOSURE_NOTICE =
  "This audio was generated by artificial intelligence (AI). It is not a recording of a human speaker.";

export type VoiceDisclosureKind = "ai_generated_speech" | "ai_transcription" | "ai_realtime_agent";

export interface VoiceDisclosureBlock {
  policyVersion: string;
  kind: VoiceDisclosureKind;
  label: "AI-generated speech";
  notice: string;
  providerId: string;
  modelId: string;
  voiceId: string | null;
  generatedAt: string;
}

export interface VoiceProvenanceRecord {
  id: string;
  projectId: string;
  organizationId: string;
  jobId: string | null;
  operation: string;
  providerId: string;
  modelId: string;
  voiceId: string | null;
  /** voice-safety policy version that governed the operation. */
  policyVersion: string;
  /** voice-disclosure policy version embedded in the output. */
  disclosurePolicyVersion: string;
  disclosure: VoiceDisclosureBlock;
  inputSnapshotHash: string;
  outputAssetIds: string[];
  exportManifestHash: string | null;
  createdAt: string;
}

export interface ExportManifestAssetRef {
  assetId: string;
  kind: string;
  sha256: string;
  contentType: string | null;
  durationSeconds: number | null;
}

export interface VoiceExportManifest {
  manifestVersion: 1;
  exportId: string;
  projectId: string;
  organizationId: string;
  exporterActorId: string;
  disclosure: VoiceDisclosureBlock;
  policyVersion: string;
  provenanceId: string | null;
  assets: ExportManifestAssetRef[];
  createdAt: string;
  /** SHA-256 over the canonical serialization of the manifest fields. */
  manifestHash: string;
}
