import type {
  CustomerProfile,
  KnowledgeArticle,
  AiSuggestion,
  SupportTicket,
  TicketMessage,
  HistoryEvent,
  CustomerSupportState,
} from "./state";

const TICKETS: SupportTicket[] = [
  {
    id: "CS-1048",
    subject: "Headphone ANC stopped working after firmware update",
    customerId: "C-1001",
    customerName: "Riley Green",
    customerInitials: "RG",
    accountTier: "premium",
    channel: "email",
    status: "open",
    priority: "high",
    sentiment: "negative",
    sla: { state: "at_risk", dueAt: "2026-06-18T14:30:00Z", label: "45m remaining" },
    assignee: null,
    team: "Hardware Support",
    tags: ["audio", "firmware", "anc", "warranty"],
    lastMessage: "I've tried resetting three times and the noise cancellation is still broken.",
    lastActivity: "3m ago",
    unread: true,
    ai: {
      summary: "Customer reports ANC failure on QC-45 headphones after applying firmware v3.2.1 update. Multiple resets attempted without improvement.",
      intent: "Product defect / firmware regression",
      confidence: "high",
      suggestedPriority: "High",
      suggestedTeam: "Hardware Tier 2",
      riskReasons: ["Premium account", "SLA at risk", "Repeat hardware issue"],
      sources: ["QC-45 Troubleshooting Guide v2", "Firmware v3.2.1 Release Notes", "Similar ticket #CS-1022"],
    },
    category: "hardware",
    description: "After updating firmware to v3.2.1, the active noise cancellation stopped working entirely. Customer has factory reset twice and power cycled three times.",
    createdAt: "2026-06-17T09:15:00Z",
    updatedAt: "2026-06-18T10:30:00Z",
  },
  {
    id: "CS-1045",
    subject: "Subscription upgrade not reflecting in account",
    customerName: "Morgan Chase",
    customerInitials: "MC",
    accountTier: "enterprise",
    channel: "chat",
    status: "open",
    priority: "critical",
    sentiment: "angry",
    sla: { state: "at_risk", dueAt: "2026-06-18T13:00:00Z", label: "18m remaining" },
    assignee: "Alex Chen",
    team: "Billing Support",
    tags: ["billing", "subscription", "upgrade", "finance"],
    customerId: "C-1002",
    lastMessage: "This is the second time I'm asking. Our CFO is waiting for the invoice.",
    lastActivity: "8m ago",
    unread: true,
    ai: {
      summary: "Enterprise account upgraded from Pro to Enterprise plan, but billing portal still shows old plan. Payment already processed but invoice not reflecting correct tier.",
      intent: "Billing sync failure",
      confidence: "high",
      suggestedPriority: "Critical",
      suggestedTeam: "Billing Support",
      riskReasons: ["Enterprise account", "CFO visibility", "SLA imminent breach", "Repeat contact"],
      sources: ["Billing Integration Guide", "Enterprise SLA Policy", "Subscription Management KB"],
    },
    category: "billing",
    description: "Our account was upgraded to Enterprise plan yesterday, but the billing portal still shows the old Pro plan. The payment has already been processed, and the CFO needs the corrected invoice for quarterly close.",
    createdAt: "2026-06-16T14:20:00Z",
    updatedAt: "2026-06-18T11:15:00Z",
  },
  {
    id: "CS-1042",
    subject: "Can't access shared documents from mobile app",
    customerName: "Jamie Kim",
    customerInitials: "JK",
    accountTier: "standard",
    channel: "portal",
    status: "open",
    priority: "normal",
    sentiment: "neutral",
    sla: { state: "healthy", dueAt: "2026-06-19T10:00:00Z", label: "21h remaining" },
    assignee: null,
    team: "General Support",
    tags: ["mobile", "access", "documents"],
    customerId: "C-1003",
    lastMessage: "The desktop version works fine, but the mobile app just shows a loading spinner.",
    lastActivity: "1h ago",
    unread: false,
    ai: {
      summary: "Customer can access shared documents on desktop but mobile app fails to load document list. Likely mobile API session timeout issue.",
      intent: "Mobile app access issue",
      confidence: "medium",
      suggestedPriority: "Normal",
      suggestedTeam: "General Support",
      riskReasons: ["Possible mobile client bug", "Only affects mobile"],
      sources: ["Mobile App Troubleshooting", "Known Issue #KI-47: Mobile session timeout"],
    },
    category: "software",
    description: "Since the last mobile app update, I cannot access shared documents. Works perfectly on desktop. Mobile app shows loading spinner indefinitely.",
    createdAt: "2026-06-17T16:45:00Z",
    updatedAt: "2026-06-18T09:20:00Z",
  },
  {
    id: "CS-1039",
    subject: "Refund request for duplicate charge",
    customerName: "Taylor Reed",
    customerInitials: "TR",
    accountTier: "vip",
    channel: "email",
    status: "escalated",
    priority: "high",
    sentiment: "at_risk",
    sla: { state: "breached", dueAt: "2026-06-17T18:00:00Z", label: "Breached" },
    assignee: "Sam Wilson",
    team: "Billing Support",
    tags: ["billing", "refund", "duplicate", "escalated"],
    customerId: "C-1004",
    lastMessage: "I want this escalated. I've been waiting three days for a simple refund.",
    lastActivity: "2h ago",
    unread: true,
    ai: {
      summary: "VIP customer charged twice for annual subscription. Refund requested 3 days ago. Billing team investigating. Customer is escalating due to delay.",
      intent: "Duplicate charge refund",
      confidence: "low",
      suggestedPriority: "High",
      suggestedTeam: "Billing Support",
      riskReasons: ["VIP account", "Refund over threshold", "SLA breached", "Customer threatening churn"],
      sources: ["Refund Policy v4", "VIP Account Handling SOP", "Payment Integration Guide"],
    },
    category: "billing",
    description: "I was charged twice for my annual subscription renewal. Requested refund 3 days ago but still no resolution. This is unacceptable for a VIP account.",
    createdAt: "2026-06-14T11:30:00Z",
    updatedAt: "2026-06-18T08:00:00Z",
  },
  {
    id: "CS-1036",
    subject: "How to set up team permissions for new workspace?",
    customerName: "Jordan Blake",
    customerInitials: "JB",
    accountTier: "premium",
    channel: "chat",
    status: "waiting_on_customer",
    priority: "low",
    sentiment: "positive",
    sla: { state: "healthy", dueAt: "2026-06-20T15:00:00Z", label: "2d remaining" },
    assignee: "Alex Chen",
    team: "General Support",
    tags: ["setup", "permissions", "workspace"],
    customerId: "C-1005",
    lastMessage: "Great, that helped! I'll check with my admin and get back to you.",
    lastActivity: "1d ago",
    unread: false,
    ai: {
      summary: "Customer asking about best practices for setting up team permissions in a new workspace. Agent provided workspace roles documentation. Customer is testing and will follow up.",
      intent: "Workspace configuration guidance",
      confidence: "high",
      suggestedPriority: "Low",
      suggestedTeam: "General Support",
      riskReasons: [],
      sources: ["Workspace Roles KB", "Admin Setup Guide v2"],
    },
    category: "setup",
    description: "We just created a new workspace for our design team. What's the recommended way to set up role-based permissions?",
    createdAt: "2026-06-16T09:00:00Z",
    updatedAt: "2026-06-17T15:30:00Z",
  },
  {
    id: "CS-1033",
    subject: "Integration with Salesforce not syncing contacts",
    customerName: "Avery Patel",
    customerInitials: "AP",
    accountTier: "enterprise",
    channel: "email",
    status: "open",
    priority: "high",
    sentiment: "negative",
    sla: { state: "healthy", dueAt: "2026-06-19T08:00:00Z", label: "18h remaining" },
    assignee: null,
    team: "Integrations Support",
    tags: ["integration", "salesforce", "sync"],
    customerId: "C-1006",
    lastMessage: "The sync has been stuck for 6 hours. Our sales team can't see new support contacts.",
    lastActivity: "4h ago",
    unread: true,
    ai: {
      summary: "Salesforce integration stopped syncing contact records. No error shown in integration dashboard. Manual sync button also fails silently.",
      intent: "Integration sync failure",
      confidence: "medium",
      suggestedPriority: "High",
      suggestedTeam: "Integrations Support",
      riskReasons: ["Enterprise account", "Sales team impact", "Silent failure mode"],
      sources: ["Salesforce Integration Guide", "Integration Troubleshooting KB", "Known Issue #KI-52: OAuth token expiry"],
    },
    category: "integration",
    description: "Our Salesforce integration stopped syncing contact records about 6 hours ago. The integration dashboard shows 'Connected' but no recent sync activity. Manual sync fails silently.",
    createdAt: "2026-06-17T07:30:00Z",
    updatedAt: "2026-06-18T06:45:00Z",
  },
];

const CUSTOMERS: CustomerProfile[] = [
  {
    id: "C-1001",
    name: "Riley Green",
    email: "riley.green@example.com",
    company: "Green Audio Solutions",
    tier: "premium",
    health: "watch",
    sentimentTrend: "declining",
    previousTickets: 8,
    openTickets: 2,
    satisfaction: 3.8,
    preferredChannel: "email",
    language: "en",
    location: "Austin, TX",
    timezone: "America/Chicago",
    avatarInitials: "RG",
  },
  {
    id: "C-1002",
    name: "Morgan Chase",
    email: "morgan.chase@financetech.io",
    company: "FinanceTech Inc.",
    tier: "enterprise",
    health: "at_risk",
    sentimentTrend: "declining",
    previousTickets: 15,
    openTickets: 3,
    satisfaction: 3.2,
    preferredChannel: "chat",
    language: "en",
    location: "New York, NY",
    timezone: "America/New_York",
    avatarInitials: "MC",
  },
  {
    id: "C-1003",
    name: "Jamie Kim",
    email: "jamie.kim@creativestudio.io",
    company: "Creative Studio Co.",
    tier: "standard",
    health: "healthy",
    sentimentTrend: "stable",
    previousTickets: 3,
    openTickets: 1,
    satisfaction: 4.5,
    preferredChannel: "portal",
    language: "en",
    location: "San Francisco, CA",
    timezone: "America/Los_Angeles",
    avatarInitials: "JK",
  },
  {
    id: "C-1004",
    name: "Taylor Reed",
    email: "taylor.reed@luxurybrands.com",
    company: "Luxury Brands Group",
    tier: "vip",
    health: "at_risk",
    sentimentTrend: "declining",
    previousTickets: 22,
    openTickets: 4,
    satisfaction: 2.8,
    preferredChannel: "email",
    language: "en",
    location: "London, UK",
    timezone: "Europe/London",
    avatarInitials: "TR",
  },
  {
    id: "C-1005",
    name: "Jordan Blake",
    email: "jordan.blake@startup.io",
    company: "Startup Labs",
    tier: "premium",
    health: "healthy",
    sentimentTrend: "improving",
    previousTickets: 5,
    openTickets: 1,
    satisfaction: 4.8,
    preferredChannel: "chat",
    language: "en",
    location: "Berlin, Germany",
    timezone: "Europe/Berlin",
    avatarInitials: "JB",
  },
  {
    id: "C-1006",
    name: "Avery Patel",
    email: "avery.patel@globalent.com",
    company: "Global Enterprise Ltd.",
    tier: "enterprise",
    health: "watch",
    sentimentTrend: "declining",
    previousTickets: 12,
    openTickets: 2,
    satisfaction: 3.5,
    preferredChannel: "email",
    language: "en",
    location: "Singapore",
    timezone: "Asia/Singapore",
    avatarInitials: "AP",
  },
];

const MESSAGES: TicketMessage[] = [
  { id: "M-1001", ticketId: "CS-1048", type: "customer", author: "Riley Green", body: "Hi, I just updated the firmware on my QC-45 headphones to version 3.2.1, and now the active noise cancellation doesn't work at all. I can hear everything around me. Can you help?", createdAt: "2026-06-17T09:15:00Z" },
  { id: "M-1002", ticketId: "CS-1048", type: "agent", author: "Alex Chen", body: "Hello Riley, sorry to hear about the issue. Let me help you troubleshoot. First, have you tried a factory reset? Hold the power button for 15 seconds until you hear 'factory reset'. Then re-pair with your device.", createdAt: "2026-06-17T10:30:00Z" },
  { id: "M-1003", ticketId: "CS-1048", type: "customer", author: "Riley Green", body: "Yes, I've tried that three times actually. I also unpaired and re-paired with my phone. The ANC still doesn't engage. The headphones work fine otherwise — they play audio, just no noise cancellation.", createdAt: "2026-06-17T14:00:00Z" },
  { id: "M-1004", ticketId: "CS-1048", type: "internal_note", author: "Alex Chen", body: "Possible firmware regression. Need to check with hardware team if v3.2.1 has known ANC issues. Tagging Hardware Tier 2.", createdAt: "2026-06-17T14:05:00Z" },
  { id: "M-1005", ticketId: "CS-1048", type: "agent", author: "Alex Chen", body: "Thank you for trying those steps. I'm escalating this to our hardware specialist team. They'll review the firmware version and get back to you with a solution. In the meantime, you can downgrade the firmware to v3.2.0 using the desktop app if you'd like ANC restored sooner.", createdAt: "2026-06-17T15:00:00Z" },
  { id: "M-1006", ticketId: "CS-1048", type: "customer", author: "Riley Green", body: "I've tried resetting three times and the noise cancellation is still broken.", createdAt: "2026-06-18T10:30:00Z" },
  { id: "M-2001", ticketId: "CS-1045", type: "customer", author: "Morgan Chase", body: "We upgraded our plan from Pro to Enterprise yesterday. Payment went through, but the billing dashboard still shows Pro. I need the corrected invoice ASAP for our CFO.", createdAt: "2026-06-16T14:20:00Z" },
  { id: "M-2002", ticketId: "CS-1045", type: "agent", author: "Sam Wilson", body: "Hi Morgan, I can see the upgrade request and the payment. Let me check why the billing portal hasn't updated. This may be a sync delay between our systems.", createdAt: "2026-06-16T16:00:00Z" },
  { id: "M-2003", ticketId: "CS-1045", type: "internal_note", author: "Sam Wilson", body: "Billing API seems to have a sync lag. Checking with engineering team. This is a known issue with high-value account upgrades.", createdAt: "2026-06-17T09:00:00Z" },
  { id: "M-2004", ticketId: "CS-1045", type: "customer", author: "Morgan Chase", body: "This is the second time I'm asking. Our CFO is waiting for the invoice.", createdAt: "2026-06-18T11:15:00Z" },
  { id: "M-3001", ticketId: "CS-1039", type: "customer", author: "Taylor Reed", body: "I was charged twice for my annual subscription renewal. I need a refund for the duplicate charge immediately.", createdAt: "2026-06-14T11:30:00Z" },
  { id: "M-3002", ticketId: "CS-1039", type: "agent", author: "Sam Wilson", body: "Hello Taylor, I see the duplicate charge. Refund requests over $500 require additional verification. I've started the process and will update you within 24 hours.", createdAt: "2026-06-14T14:00:00Z" },
  { id: "M-3003", ticketId: "CS-1039", type: "customer", author: "Taylor Reed", body: "It's been 48 hours. What is going on? I want this escalated right now.", createdAt: "2026-06-16T09:00:00Z" },
  { id: "M-3004", ticketId: "CS-1039", type: "internal_note", author: "Sam Wilson", body: "Refund requires manager approval due to VIP account and amount over $1k. Billing manager is OOO until Monday. Need to find backup approver.", createdAt: "2026-06-16T09:30:00Z" },
  { id: "M-3005", ticketId: "CS-1039", type: "customer", author: "Taylor Reed", body: "I want this escalated. I've been waiting three days for a simple refund.", createdAt: "2026-06-18T08:00:00Z" },
];

const KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  { id: "KB-101", title: "QC-45 Troubleshooting Guide", category: "hardware", summary: "Step-by-step troubleshooting for QC-45 headphone issues", snippet: "If ANC stops working after a firmware update, first try a factory reset. If the issue persists, downgrade to the previous firmware version using the desktop companion app. Known issue with v3.2.1 affecting ANC DSP module.", source: "Hardware Support Team", lastUpdated: "2026-06-10", matchScore: 94, freshness: "fresh", usageCount: 142 },
  { id: "KB-102", title: "Firmware v3.2.1 Release Notes", category: "software", summary: "Release notes and known issues for firmware v3.2.1", snippet: "Known issue: ANC DSP initialization may fail on some units post-update. Affects QC-45 and QC-55 models. Workaround: power cycle and re-pair. Fix expected in v3.2.2.", source: "Engineering Team", lastUpdated: "2026-06-01", matchScore: 88, freshness: "fresh", usageCount: 67 },
  { id: "KB-103", title: "Billing Sync Troubleshooting", category: "billing", summary: "How to resolve billing portal sync issues after plan changes", snippet: "If the billing portal does not reflect a recent plan upgrade, first verify the payment was processed. Billing API sync typically completes within 2 hours. For delays beyond 4 hours, contact the billing integrations team.", source: "Billing Team", lastUpdated: "2026-05-28", matchScore: 91, freshness: "fresh", usageCount: 203 },
  { id: "KB-104", title: "Enterprise SLA Policy", category: "operations", summary: "SLA commitments and escalation procedures for Enterprise accounts", snippet: "Enterprise accounts have a 4-hour SLA for critical tickets and 8-hour for high priority. SLA breach triggers automatic escalation to account manager.", source: "Operations", lastUpdated: "2026-04-15", matchScore: 85, freshness: "fresh", usageCount: 98 },
  { id: "KB-105", title: "Refund Policy v4", category: "billing", summary: "Current refund policy, thresholds, and approval workflows", snippet: "Refunds up to $500 can be processed by agents. Refunds $500-$2,000 require team lead approval. Refunds over $2,000 require manager approval and compliance review. VIP account refunds always require manager approval regardless of amount.", source: "Finance Team", lastUpdated: "2026-05-01", matchScore: 96, freshness: "fresh", usageCount: 312 },
  { id: "KB-106", title: "Salesforce Integration Setup Guide", category: "integration", summary: "Complete setup guide for Salesforce integration", snippet: "The integration uses OAuth 2.0 for authentication. Token expiry is 60 days. If the sync stops, check the integration dashboard for token status. Manual re-authentication is available in Settings > Integrations > Salesforce.", source: "Engineering Team", lastUpdated: "2026-03-20", matchScore: 79, freshness: "stale_warning", usageCount: 156 },
  { id: "KB-107", title: "Mobile App Troubleshooting Guide", category: "software", summary: "Common mobile app issues and their resolutions", snippet: "If documents fail to load on mobile but work on desktop, check the app version. Known issue KI-47 affects app versions 4.2.0-4.2.3. Update to 4.2.4 or clear app cache to resolve.", source: "Mobile Team", lastUpdated: "2026-06-05", matchScore: 82, freshness: "fresh", usageCount: 89 },
  { id: "KB-108", title: "Workspace Roles and Permissions Guide", category: "setup", summary: "Best practices for configuring workspace roles", snippet: "Recommended workspace roles: Admin, Member, Guest. For design teams, we recommend creating custom roles with view-only access to drafts. Enterprise accounts can set up SAML-based role mapping.", source: "Product Team", lastUpdated: "2026-05-20", matchScore: 90, freshness: "fresh", usageCount: 74 },
];

const AI_SUGGESTIONS: AiSuggestion[] = [
  {
    id: "AI-1001",
    ticketId: "CS-1048",
    type: "reply",
    title: "Suggested Reply to Customer",
    recommendation: "Hi Riley,\n\nThank you for your patience. I've escalated this to our hardware specialist team who will investigate the ANC issue with firmware v3.2.1.\n\nIn the meantime, you can restore noise cancellation by downgrading to firmware v3.2.0:\n1. Open the desktop companion app\n2. Go to Settings > Device > Firmware\n3. Select 'Roll back to v3.2.0'\n4. Confirm and wait for the update to complete\n\nWe'll follow up once the hardware team has identified the root cause.",
    confidence: "high",
    risk: "low",
    sources: ["QC-45 Troubleshooting Guide v2", "Firmware v3.2.1 Release Notes"],
    missingInfo: ["Device serial number not confirmed"],
    actions: ["Insert into composer", "Edit and send", "Regenerate"],
  },
  {
    id: "AI-1002",
    ticketId: "CS-1048",
    type: "close_note",
    title: "Close Note Draft",
    recommendation: "Resolution: Firmware regression identified. Customer guided to downgrade to v3.2.0. Hardware team investigating root cause for v3.2.2 fix.\n\nRoot Cause: ANC DSP initialization failure post-firmware update.\n\nAction Taken: Escalated to Hardware Tier 2. Provided firmware rollback instructions.\n\nKB Gap: No separate article for firmware rollback procedure exists.",
    confidence: "high",
    risk: "low",
    sources: ["QC-45 Troubleshooting Guide v2"],
    missingInfo: [],
    actions: ["Apply close note", "Edit before closing"],
  },
  {
    id: "AI-1003",
    ticketId: "CS-1045",
    type: "reply",
    title: "Suggested Reply to Customer",
    recommendation: "Hi Morgan,\n\nI sincerely apologize for the delay. I've identified the issue — there's a sync delay between our billing API and the portal.\n\nI've manually triggered a sync refresh on your account. The corrected Enterprise invoice will be available in the billing portal within 30 minutes.\n\nIf you need the invoice sent directly to your CFO, please let me know and I'll email a PDF copy.",
    confidence: "high",
    risk: "medium",
    sources: ["Billing Sync Troubleshooting KB", "Enterprise SLA Policy"],
    missingInfo: ["CFO email address for direct invoice"],
    actions: ["Insert into composer", "Edit and send", "Regenerate"],
  },
  {
    id: "AI-1004",
    ticketId: "CS-1045",
    type: "field_change",
    title: "Priority and Team Update",
    recommendation: "Change priority from High to Critical — Enterprise account, CFO visibility, SLA imminent breach.",
    confidence: "high",
    risk: "low",
    sources: ["Enterprise SLA Policy"],
    missingInfo: [],
    actions: ["Apply changes", "Edit before apply"],
  },
  {
    id: "AI-1005",
    ticketId: "CS-1039",
    type: "reply",
    title: "Suggested Reply (Low Confidence)",
    recommendation: "Hi Taylor,\n\nI sincerely apologize for the wait. I understand how frustrating this is.\n\nI've escalated your refund request to our billing manager for priority processing. Given the delay, I'm also applying a 10% credit to your account as a goodwill gesture.\n\nYou should receive the refund confirmation within the next 4 hours.\n\nAgain, I apologize for the poor experience.",
    confidence: "low",
    risk: "high",
    sources: ["Refund Policy v4", "VIP Account Handling SOP"],
    missingInfo: ["Manager approval not yet obtained", "Exact duplicate charge amount not confirmed in system"],
    actions: ["Review required", "Edit carefully", "Request manager approval"],
  },
  {
    id: "AI-1006",
    ticketId: "CS-1039",
    type: "escalation",
    title: "Escalation Recommendation",
    recommendation: "Escalate to Billing Manager — VIP account, duplicate charge refund over $500, SLA breached, customer threatening churn.\n\nReason: Refund requires manager approval. Current approver is unavailable. Need backup approver or temporary override.",
    confidence: "high",
    risk: "medium",
    sources: ["Refund Policy v4", "VIP Account Handling SOP"],
    missingInfo: ["Backup approver contact"],
    actions: ["Escalate now", "Edit escalation packet", "Save as draft"],
  },
  {
    id: "AI-1007",
    ticketId: "CS-1033",
    type: "reply",
    title: "Suggested Reply",
    recommendation: "Hi Avery,\n\nThank you for reporting this. I've checked the integration status and it appears the OAuth token may have expired.\n\nPlease try the following:\n1. Go to Settings > Integrations > Salesforce\n2. Click 'Re-authenticate'\n3. Complete the OAuth flow\n\nIf the issue persists after re-authentication, please let me know and I'll escalate to our integrations engineering team.",
    confidence: "medium",
    risk: "low",
    sources: ["Salesforce Integration Setup Guide", "Known Issue KI-52: OAuth token expiry"],
    missingInfo: ["Last successful sync timestamp not confirmed", "Integration log not yet checked"],
    actions: ["Insert into composer", "Edit and send", "Regenerate"],
  },
  {
    id: "AI-1008",
    ticketId: "CS-1042",
    type: "reply",
    title: "Suggested Reply",
    recommendation: "Hi Jamie,\n\nThis sounds like it could be a known issue with the mobile app. Can you check your app version?\n\nGo to Settings > About and check if the version is between 4.2.0 and 4.2.3. If so, updating to version 4.2.4 should resolve the issue.\n\nIf you're already on 4.2.4, please try clearing the app cache:\n1. Go to Settings > Apps > Clear Cache\n2. Restart the app\n\nLet me know if this helps!",
    confidence: "high",
    risk: "low",
    sources: ["Mobile App Troubleshooting Guide", "Known Issue KI-47"],
    missingInfo: ["Current app version not verified"],
    actions: ["Insert into composer", "Edit and send", "Regenerate"],
  },
];

const HISTORY_EVENTS: HistoryEvent[] = [
  { id: "H-1001", ticketId: "CS-1022", ticketSubject: "QC-45 left driver stopped working", type: "ticket", summary: "Replacement unit sent under warranty", date: "2026-05-10", status: "resolved" },
  { id: "H-1002", ticketId: "CS-1008", ticketSubject: "Bluetooth pairing issues with MacBook", type: "ticket", summary: "Firmware reinstall resolved the issue", date: "2026-04-22", status: "resolved" },
  { id: "H-1003", ticketId: "CS-1041", ticketSubject: "Account access recovery", type: "ticket", summary: "Password reset and 2FA reconfiguration", date: "2026-06-15", status: "resolved" },
  { id: "H-1004", ticketId: "CS-1040", ticketSubject: "Payment method update", type: "interaction", summary: "Chat interaction about changing billing method", date: "2026-06-12", status: "resolved" },
  { id: "H-1005", ticketId: "CS-1020", ticketSubject: "Integration webhook failure", type: "ticket", summary: "Webhook URL updated, sync restored", date: "2026-05-28", status: "closed" },
  { id: "H-1006", ticketId: "CS-1025", ticketSubject: "Refund for incorrect charge", type: "refund", summary: "Partial refund processed", date: "2026-05-15", status: "refunded" },
  { id: "H-1007", ticketId: "CS-1030", ticketSubject: "Feature request: bulk export", type: "ticket", summary: "Escalated to product team for consideration", date: "2026-06-01", status: "escalated" },
  { id: "H-1008", ticketId: "CS-1015", ticketSubject: "Satisfaction survey response", type: "csat", summary: "Customer rated 4/5 — good resolution", date: "2026-05-20", status: "positive" },
  { id: "H-1009", ticketId: "CS-1037", ticketSubject: "API rate limit concern", type: "ticket", summary: "Rate limit increased for Enterprise plan", date: "2026-06-14", status: "resolved" },
  { id: "H-1010", ticketId: "CS-1038", ticketSubject: "Account note after phone call", type: "note", summary: "Customer mentioned upcoming team expansion", date: "2026-06-11", status: "resolved" },
];

export const CUSTOMER_SUPPORT_FIXTURE: CustomerSupportState = {
  tickets: TICKETS,
  messages: MESSAGES,
  customers: CUSTOMERS,
  knowledgeArticles: KNOWLEDGE_ARTICLES,
  aiSuggestions: AI_SUGGESTIONS,
  historyEvents: HISTORY_EVENTS,
  selectedTicketId: null,
  activeView: "inbox",
  rightPanelOpen: false,
  rightPanelTab: "ai-assist",
};
