/**
 * Studio V2 Job 02 — owned output ingest.
 * Provider bytes become owned immutable assets: L0 technical checks,
 * idempotent tenant-object store, studio_assets row (correct columns),
 * provider_source variant + lineage edge, and a Job-01 decision lock as
 * the candidate-acceptance record. Every seam is injectable for tests.
 */

import "server-only";

import { randomUUID } from "node:crypto";
import { uploadTenantObject } from "@ethen/database/storage/tenant-object-storage";
import { getStudioRepository } from "./persistence/studio-repository";
import { lockDecision } from "./creative-graph/service";
import { recordAssetLineageDurable, recordAssetVariantDurable, type AssetLineageEdge, type AssetVariant } from "./lineage";
import { validateStudioUpload } from "./storage/uploads";

export interface IngestScope {
  organizationId: string;
  projectId: string;
  actorId: string;
}

export interface IngestInput {
  bytes: Uint8Array;
  contentType: string;
  filename: string;
  idempotencyKey: string;
  jobId: string;
  providerId: string;
  modelId: string;
  promptHash: string;
}

export interface IngestResult {
  assetId: string;
  variantId: string;
  objectKey: string;
  contentHash: string;
  byteSize: number;
  mimeType: string;
  width: number | null;
  height: number | null;
  lockId: string;
}

export interface ImageIngestDeps {
  storeBytes?(input: {
    projectId: string;
    actorId: string;
    bytes: Uint8Array;
    contentType: string;
    filename: string;
    idempotencyKey: string;
  }): Promise<{ objectKey: string }>;
  recordVariant?(scope: IngestScope, input: Omit<AssetVariant, "id" | "createdAt" | "immutable">): Promise<AssetVariant>;
  recordEdge?(scope: IngestScope, input: Omit<AssetLineageEdge, "id" | "createdAt" | "immutable">): Promise<AssetLineageEdge>;
}

async function defaultStoreBytes(input: {
  projectId: string; actorId: string; bytes: Uint8Array; contentType: string; filename: string; idempotencyKey: string;
}): Promise<{ objectKey: string }> {
  const stored = await uploadTenantObject({
    projectId: input.projectId,
    actorId: input.actorId,
    bytes: input.bytes,
    contentType: input.contentType,
    filename: input.filename,
    source: "studio",
    retentionDays: 90,
    idempotencyKey: input.idempotencyKey,
  });
  return { objectKey: stored.objectKey };
}

/**
 * Ingest one generated image. Throws IMAGE_INGEST_* on L0 failure —
 * callers decide liability (post-send failures retain the reservation).
 */
export async function ingestGeneratedImage(
  scope: IngestScope,
  input: IngestInput,
  deps: ImageIngestDeps = {},
): Promise<IngestResult> {
  if (!scope.organizationId?.trim() || !scope.projectId?.trim() || !scope.actorId?.trim()) {
    throw new Error("IMAGE_INGEST_INVALID: organizationId, projectId, and actorId are required.");
  }
  if (!(input.bytes instanceof Uint8Array) || input.bytes.byteLength === 0) {
    throw new Error("IMAGE_INGEST_INVALID: generated bytes are empty.");
  }
  const mimeType = input.contentType?.trim() || "image/png";
  let metadata;
  try {
    metadata = validateStudioUpload(input.bytes, mimeType, input.filename);
  } catch (error) {
    throw new Error(`IMAGE_INGEST_L0_REJECTED: ${error instanceof Error ? error.message : "L0 checks failed."}`);
  }

  const storeBytes = deps.storeBytes ?? defaultStoreBytes;
  const stored = await storeBytes({
    projectId: scope.projectId, actorId: scope.actorId,
    bytes: input.bytes, contentType: metadata.mimeType, filename: input.filename,
    idempotencyKey: input.idempotencyKey,
  });

  const repo = getStudioRepository();
  const assetId = randomUUID();
  const at = new Date().toISOString();
  try {
    await repo.insert(scope, "studio_assets", {
      id: assetId,
      payload: {
        asset_kind: "generation",
        content_hash: metadata.sha256,
        metadata: {
          name: input.filename, providerId: input.providerId, modelId: input.modelId,
          jobId: input.jobId, promptHash: input.promptHash, mimeType: metadata.mimeType,
          width: metadata.width ?? null, height: metadata.height ?? null, objectKey: stored.objectKey,
        },
        lineage: { provider: input.providerId, jobId: input.jobId },
      },
      createdAt: at,
      updatedAt: at,
      deletedAt: null,
    });
  } catch (error) {
    // Idempotent replay: the asset row already exists for this ingest key.
    // Resolve it by content hash rather than failing the ingest.
    const message = error instanceof Error ? error.message : String(error);
    if (!/unique|duplicate|23505|already exists/i.test(message)) throw error;
    const existing = await repo.list(scope, "studio_assets");
    const match = existing.find((row) => ((row.payload as Record<string, unknown>).content_hash as string) === metadata.sha256);
    if (!match) throw error;
    return ingestAcceptance(scope, match.id, stored.objectKey, metadata.sha256, input.bytes.byteLength, metadata.mimeType, metadata.width ?? null, metadata.height ?? null);
  }

  const recordVariant = deps.recordVariant ?? recordAssetVariantDurable;
  const variant = await recordVariant(scope, {
    assetId, projectId: scope.projectId, ownerId: scope.actorId,
    kind: "provider_source", storageKey: stored.objectKey,
    contentHash: metadata.sha256, mimeType: metadata.mimeType, byteSize: input.bytes.byteLength,
  });
  const recordEdge = deps.recordEdge ?? recordAssetLineageDurable;
  await recordEdge(scope, {
    projectId: scope.projectId, ownerId: scope.actorId,
    outputAssetId: assetId, jobId: input.jobId,
    transform: `generate:${input.providerId}:${input.modelId}`, inputSnapshotHash: input.promptHash,
  });
  return ingestAcceptance(scope, assetId, stored.objectKey, metadata.sha256, input.bytes.byteLength, metadata.mimeType, metadata.width ?? null, metadata.height ?? null, variant.id);
}

/**
 * Recovery lookup: the ingested asset for a job, if a prior attempt stored
 * one. Matches on metadata.jobId so reclaim never double-ingests.
 */
export async function findIngestedAsset(
  scope: IngestScope,
  jobId: string,
): Promise<{ assetId: string; objectKey: string; contentHash: string } | null> {
  const repo = getStudioRepository();
  const rows = await repo.list(scope, "studio_assets");
  for (const row of rows) {
    const metadata = ((row.payload as Record<string, unknown>).metadata ?? {}) as Record<string, unknown>;
    if (metadata.jobId !== jobId) continue;
    const data = row.payload as Record<string, unknown>;
    return {
      assetId: row.id,
      objectKey: typeof metadata.objectKey === "string" ? (metadata.objectKey as string) : "",
      contentHash: typeof data.content_hash === "string" ? (data.content_hash as string) : "",
    };
  }
  return null;
}

async function ingestAcceptance(
  scope: IngestScope,
  assetId: string,
  objectKey: string,
  contentHash: string,
  byteSize: number,
  mimeType: string,
  width: number | null,
  height: number | null,
  variantId?: string,
): Promise<IngestResult> {
  const repo = getStudioRepository();
  const lock = await lockDecision(repo, scope, {
    entityKind: "asset", entityId: assetId, entityRevision: 1, payloadHash: contentHash,
  }, `accept-${assetId.slice(0, 8)}-${contentHash.slice(0, 12)}`);
  return {
    assetId, variantId: variantId ?? "", objectKey, contentHash, byteSize, mimeType, width, height,
    lockId: lock.record.id,
  };
}
