import type { CodingToolDefinition } from "@ethen/contracts/tools/types";

export const CODING_TOOLS: CodingToolDefinition[] = [
  {
    id: "repo.get_metadata",
    label: "Repo Metadata",
    description: "Read repository name, language, and top-level config.",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "repo.list_tree",
    label: "List Tree",
    description: "List the directory tree of the connected repository.",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "repo.read_file",
    label: "Read File",
    description: "Read the contents of a single file from the repository.",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "repo.search_files",
    label: "Search Files",
    description: "Search for files or symbols by name or pattern.",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "git.status",
    label: "Git Status",
    description: "Read the current git working-tree status (no mutations).",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "git.status",
    label: "Git Status",
    description: "Read the current git working-tree status (no mutations).",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "git.status",
    label: "Git Status",
    description: "Read the current git working-tree status (no mutations).",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "git.status",
    label: "Git Status",
    description: "Read the current git working-tree status (no mutations).",
    riskTier: "read",
    defaultDecision: "allow",
    readOnly: true,
    enabled: true,
  },
  {
    id: "file.propose_patch",
    label: "Propose Patch",
    description: "Propose a file change patch with before-content hashing. Requires approval before application.",
    riskTier: "propose",
    defaultDecision: "ask",
    readOnly: true,
    enabled: true,
  },
  {
    id: "file.apply_patch",
    label: "Apply Patch",
    description: "Apply an approved patch proposal with checkpoint, atomic writes, and read-back verification.",
    riskTier: "write",
    defaultDecision: "ask",
    readOnly: false,
    enabled: true,
  },
];
