import type { AgentRegistryEntry } from "./types";

export const WAVE1_REGISTRY: AgentRegistryEntry[] = [
  {
    slug: "backup-recovery-validation-agent",
    name: "Backup & Recovery Validation Agent",
    category: "infrastructure",
    description: "Validate that your backups are recoverable before disaster strikes.",
    longDescription:
      "Ingests backup inventories, classifies asset criticality, checks RPO/RTO compliance, flags stale or untested backups, scores readiness, and generates remediation plans. Operates in read-only demo mode.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual", "scheduled"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "bi-analytics-agent",
    name: "BI Analytics Agent",
    category: "data",
    description: "Ask questions about your data and get instant visualizations and insights.",
    longDescription:
      "Upload datasets, ask questions in plain language, and receive charts, insight briefs, and follow-up suggestions. Supports CSV upload, auto-profiling, and export to markdown. Mock data only.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "communications-messaging-agent",
    name: "Communications Agent",
    category: "operations",
    description: "Orchestrate multi-channel messages and manage communication templates.",
    longDescription:
      "Drafts multi-channel campaigns, checks brand compliance, generates message variants, and produces approval packets. Draft/propose mode only.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual", "scheduled"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "customer-support-agent",
    name: "Customer Support Agent",
    category: "operations",
    description: "Resolve tickets faster with AI-powered triage, responses, and knowledge routing.",
    longDescription:
      "Ingests support tickets, classifies intent and sentiment, searches a mock knowledge base, drafts grounded replies, and generates handoff packets for escalation. Draft mode only.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual", "webhook"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "developer-deployment-agent",
    name: "Developer Deployment Agent",
    category: "developer-tools",
    description: "Manage frontend deployments, previews, and release workflows.",
    longDescription:
      "Ingests deployment logs, diagnoses failures, classifies root causes, and generates release readiness packets. Diagnose-only mode.",
    lifecycle: "draft",
    sourceCompany: "Vercel",
    buildWave: 1,
    supportedTriggers: ["manual", "webhook", "event_driven"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "developer-platform-agent",
    name: "Developer Platform Agent",
    category: "developer-tools",
    description: "Manage dev environments, monitor platform health, and onboard teams faster.",
    longDescription:
      "Ingests service catalogs, generates service profiles, checks ownership and documentation gaps, and produces developer onboarding checklists. Read-only mode.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual", "scheduled"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "document-workflow-agent",
    name: "Document Workflow Agent",
    category: "operations",
    description: "Create, review, approve, and sign documents without leaving your workflow.",
    longDescription:
      "Uploads documents, classifies type, extracts clauses, compares to playbooks, identifies risks, and generates review memos and approval packets. Draft/review mode only.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "experimentation-agent",
    name: "Experimentation Agent",
    category: "data",
    description: "Design, run, and analyze A/B experiments and feature flags.",
    longDescription:
      "Validates experiment design, analyzes results with statistical rigor, flags underpowered tests, and generates experiment reports with recommendations. Read-only analysis mode.",
    lifecycle: "draft",
    sourceCompany: "Statsig",
    buildWave: 1,
    supportedTriggers: ["manual", "scheduled"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "it-service-desk-agent",
    name: "IT Service Desk Agent",
    category: "operations",
    description: "Resolve employee IT tickets faster with intelligent triage and automation.",
    longDescription:
      "Ingests IT tickets, classifies type and urgency, retrieves mock KB resolutions, drafts employee replies, and routes escalations. Triage/draft mode only.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual", "webhook"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "project-work-agent",
    name: "Project Work Agent",
    category: "operations",
    description: "Automate project status tracking, task assignments, and progress reporting.",
    longDescription:
      "Ingests task lists, determines status, detects blockers, generates project status reports, and suggests action items. Read-only/demo mode.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual", "scheduled"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "recruiting-automation-agent",
    name: "Recruiting Automation Agent",
    category: "people-ops",
    description: "Automate recruiting workflows from sourcing to offer.",
    longDescription:
      "Ingests job descriptions and candidate profiles, screens candidates, ranks matches, suggests interview plans, and generates candidate summaries. Draft/recommend mode only.",
    lifecycle: "draft",
    sourceCompany: "Handshake",
    buildWave: 1,
    supportedTriggers: ["manual", "scheduled", "event_driven"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
  {
    slug: "workflow-automation-agent",
    name: "Workflow Automation Agent",
    category: "operations",
    description: "Design, run, and monitor cross-application business process automations.",
    longDescription:
      "Ingests process descriptions, identifies triggers and actions, maps workflow steps, detects bottlenecks, and produces automation proposals and approval packets. Draft/propose mode only.",
    lifecycle: "draft",
    sourceCompany: "established",
    buildWave: 1,
    supportedTriggers: ["manual"],
    allowedToolIds: ["agent.runtime"],
    implementationStatus: "not_started",
  },
];
