import type {
  ProjectSummary,
  ProjectTask,
  ProjectBlocker,
  ProjectDependency,
  ActionPlanItem,
  ProjectWorkState,
} from "./state";

export const DEFAULT_PROJECT: ProjectSummary = {
  id: "proj-001",
  name: "Developer Platform v2 Launch",
  lead: "Diana Reyes",
  sponsor: "Marcus Okonkwo",
  health: "at_risk",
  phase: "Beta",
  targetDate: "2026-09-15",
  progressPercent: 55,
  openBlockers: 3,
  upcomingMilestone: "Infrastructure hardening complete",
  lastUpdated: "2026-06-16T10:30:00Z",
};

let _counter = 100;
function nid(prefix: string): string {
  _counter += 1;
  return `${prefix}-${_counter}`;
}

export const DEFAULT_TASKS: ProjectTask[] = [
  {
    id: nid("task"),
    title: "Finalize OAuth2 provider onboarding flow",
    description:
      "Complete the OAuth2 consent screen, token exchange, and session management for Google and GitHub providers.",
    owner: "Priya Kapoor",
    status: "in_review",
    priority: "high",
    dueDate: "2026-07-01",
    phase: "Beta",
    progressPercent: 85,
    blockedBy: [],
    dependsOn: [],
    unblocks: ["task-110"],
    nextAction: "Address review comments from security audit",
    lastUpdated: "2026-06-15T14:00:00Z",
  },
  {
    id: nid("task"),
    title: "Implement API rate limiting middleware",
    description:
      "Add token-bucket rate limiting at the gateway layer with per-tenant and per-endpoint configuration.",
    owner: "James Liu",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-07-05",
    phase: "Beta",
    progressPercent: 45,
    blockedBy: ["blocker-105"],
    dependsOn: [],
    unblocks: ["task-111"],
    nextAction: "Integrate Redis-backed token bucket",
    lastUpdated: "2026-06-16T09:00:00Z",
  },
  {
    id: nid("task"),
    title: "Audit trail logging for all admin actions",
    description:
      "Capture every admin mutation with before/after snapshots in an append-only audit log backed by the evidence service.",
    owner: "Fatima Al-Rashid",
    status: "blocked",
    priority: "high",
    dueDate: "2026-07-08",
    phase: "Beta",
    progressPercent: 60,
    blockedBy: ["blocker-104", "blocker-106"],
    dependsOn: [],
    unblocks: [],
    nextAction: "Awaiting compliance review template",
    lastUpdated: "2026-06-10T08:30:00Z",
  },
  {
    id: nid("task"),
    title: "PCI DSS compliance self-assessment",
    description:
      "Complete SAQ-D questionnaire and collect evidence artifacts for the audited payment scope.",
    owner: "Diana Reyes",
    status: "todo",
    priority: "critical",
    dueDate: "2026-07-15",
    phase: "Beta",
    progressPercent: 15,
    blockedBy: [],
    dependsOn: [],
    unblocks: [],
    nextAction: "Schedule kickoff with QSA",
    lastUpdated: "2026-06-14T11:00:00Z",
  },
  {
    id: nid("task"),
    title: "Design service catalog UI in developer portal",
    description:
      "Create the browse, search, filter, and detail views for the service catalog inside the developer platform portal.",
    owner: "Luis Morales",
    status: "in_progress",
    priority: "medium",
    dueDate: "2026-07-10",
    phase: "Beta",
    progressPercent: 60,
    blockedBy: [],
    dependsOn: ["task-105"],
    unblocks: [],
    nextAction: "Finalize filter UX with design review",
    lastUpdated: "2026-06-15T16:00:00Z",
  },
  {
    id: nid("task"),
    title: "Provision Kubernetes namespaces via self-service API",
    description:
      "Expose a v1 endpoint that creates namespaces with default quotas, network policies, and RBAC bindings.",
    owner: "James Liu",
    status: "todo",
    priority: "medium",
    dueDate: "2026-07-18",
    phase: "Beta",
    progressPercent: 45,
    blockedBy: [],
    dependsOn: [],
    unblocks: ["task-112"],
    nextAction: "Define API contract and quota schema",
    lastUpdated: "2026-06-13T10:00:00Z",
  },
  {
    id: nid("task"),
    title: "Runbook library with automated runbook generation",
    description:
      "Build a runbook generator that produces structured markdown runbooks from service metadata and incident history.",
    owner: "Priya Kapoor",
    status: "todo",
    priority: "low",
    dueDate: "2026-08-01",
    phase: "GA",
    progressPercent: 25,
    blockedBy: [],
    dependsOn: ["task-105"],
    unblocks: [],
    nextAction: "Gather sample runbooks from SRE team",
    lastUpdated: "2026-06-12T09:00:00Z",
  },
  {
    id: nid("task"),
    title: "Implement platform usage metering and billing hooks",
    description:
      "Add usage counters per tenant and integration points for the credit/billing service to consume metered events.",
    owner: "Fatima Al-Rashid",
    status: "todo",
    priority: "medium",
    dueDate: "2026-07-25",
    phase: "GA",
    progressPercent: 45,
    blockedBy: [],
    dependsOn: ["task-104"],
    unblocks: [],
    nextAction: "Define metering schema with billing team",
    lastUpdated: "2026-06-11T14:00:00Z",
  },
  {
    id: nid("task"),
    title: "Load testing at 10x projected peak traffic",
    description:
      "Run k6 scripts against staging, establish baseline p95/p99 latencies, and publish a load-testing report.",
    owner: "James Liu",
    status: "blocked",
    priority: "high",
    dueDate: "2026-07-12",
    phase: "Beta",
    progressPercent: 45,
    blockedBy: ["blocker-105"],
    dependsOn: [],
    unblocks: [],
    nextAction: "Waiting on rate limiter to stabilize testing baseline",
    lastUpdated: "2026-06-16T07:00:00Z",
  },
  {
    id: nid("task"),
    title: "Developer onboarding guide and quickstart wizard",
    description:
      "Create a step-by-step interactive onboarding flow that creates a developer account, generates an API key, and walks through first API call.",
    owner: "Luis Morales",
    status: "backlog",
    priority: "medium",
    dueDate: "2026-08-10",
    phase: "GA",
    progressPercent: 35,
    blockedBy: [],
    dependsOn: ["task-109"],
    unblocks: [],
    nextAction: "Draft quickstart flow outline",
    lastUpdated: "2026-06-09T12:00:00Z",
  },
  {
    id: nid("task"),
    title: "Approval workflow engine for HITL actions",
    description:
      "Build a pluggable approval pipeline with configurable approver roles, timeouts, and fallback behaviors.",
    owner: "Fatima Al-Rashid",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-07-03",
    phase: "Beta",
    progressPercent: 70,
    blockedBy: [],
    dependsOn: [],
    unblocks: ["task-103"],
    nextAction: "Finalize timeout escalation rules",
    lastUpdated: "2026-06-15T18:00:00Z",
  },
  {
    id: nid("task"),
    title: "Role-based access control (RBAC) for platform admin",
    description:
      "Implement fine-grained RBAC with admin, operator, developer, and read-only roles enforced at the API and UI layers.",
    owner: "Priya Kapoor",
    status: "done",
    priority: "high",
    dueDate: "2026-06-10",
    phase: "Alpha",
    progressPercent: 100,
    blockedBy: [],
    dependsOn: [],
    unblocks: ["task-104", "task-108", "task-113"],
    nextAction: "",
    lastUpdated: "2026-06-08T17:00:00Z",
  },
  {
    id: nid("task"),
    title: "End-to-end integration test suite for critical paths",
    description:
      "Build Playwright-based e2e tests covering sign-up, API key creation, service catalog browse, approval flow, and deployment.",
    owner: "Diana Reyes",
    status: "todo",
    priority: "high",
    dueDate: "2026-07-20",
    phase: "Beta",
    progressPercent: 45,
    blockedBy: [],
    dependsOn: ["task-109"],
    unblocks: [],
    nextAction: "Define critical path test plan",
    lastUpdated: "2026-06-14T15:00:00Z",
  },
  {
    id: nid("task"),
    title: "API versioning strategy and deprecation policy",
    description:
      "Document the API versioning convention (URL path vs header), deprecation window, sunset communication template, and migration guide format.",
    owner: "Luis Morales",
    status: "cancelled",
    priority: "low",
    dueDate: "2026-06-20",
    phase: "Alpha",
    progressPercent: 100,
    blockedBy: [],
    dependsOn: [],
    unblocks: [],
    nextAction: "Revisit in GA planning",
    lastUpdated: "2026-06-05T10:00:00Z",
  },
];

export const DEFAULT_BLOCKERS: ProjectBlocker[] = [
  {
    id: "blocker-104",
    title: "Compliance review template not finalized",
    severity: "high",
    owner: "Diana Reyes",
    status: "waiting_on_decision",
    impact:
      "Audit trail logging and PCI DSS self-assessment tasks are blocked until Legal provides the approved evidence collection template.",
    resolutionPlan:
      "Escalate to sponsor for Legal prioritization. Draft interim template for engineering to proceed.",
    linkedTaskIds: ["task-103", "task-104"],
    decisionNeeded: "Legal team sign-off on audit evidence template",
    targetResolutionDate: "2026-07-01",
  },
  {
    id: "blocker-105",
    title: "Redis cluster provisioning delayed by infra team",
    severity: "high",
    owner: "James Liu",
    status: "mitigating",
    impact:
      "Rate limiting middleware and load testing blocked. Workaround using in-memory store is insufficient for distributed rate limiting.",
    resolutionPlan:
      "Infra team estimates 3 business days. James implementing with in-memory fallback for dev/staging while Redis is provisioned.",
    linkedTaskIds: ["task-102", "task-109"],
    decisionNeeded: undefined,
    targetResolutionDate: "2026-06-24",
  },
  {
    id: "blocker-106",
    title: "Third-party SIEM integration contract pending",
    severity: "medium",
    owner: "Marcus Okonkwo",
    status: "open",
    impact:
      "Audit trail log export to SIEM is blocked pending vendor agreement. Engineering can proceed with local storage and export format.",
    resolutionPlan:
      "Marcus to finalize vendor selection by end of week. Engineering will implement against standard CEF format in the meantime.",
    linkedTaskIds: ["task-103"],
    decisionNeeded: "Vendor selection for SIEM export target",
    targetResolutionDate: "2026-06-27",
  },
];

export const DEFAULT_DEPENDENCIES: ProjectDependency[] = [
  {
    id: nid("dep"),
    sourceTaskId: "task-109",
    targetTaskId: "task-110",
    type: "blocks",
    status: "active",
    risk: "medium",
    reason:
      "Load testing must complete before onboarding wizard can validate performance expectations for new user sign-ups.",
  },
  {
    id: nid("dep"),
    sourceTaskId: "task-102",
    targetTaskId: "task-111",
    type: "depends_on",
    status: "at_risk",
    risk: "high",
    reason:
      "Approval workflow engine depends on rate limiting middleware to prevent abuse of HITL approval endpoints.",
  },
  {
    id: nid("dep"),
    sourceTaskId: "task-105",
    targetTaskId: "task-106",
    type: "depends_on",
    status: "active",
    risk: "low",
    reason:
      "Service catalog UI data is populated from the Kubernetes namespace provisioning API.",
  },
  {
    id: nid("dep"),
    sourceTaskId: "task-106",
    targetTaskId: "task-108",
    type: "depends_on",
    status: "active",
    risk: "low",
    reason:
      "Billing hooks require namespace provisioning to associate tenant usage with provisioned resources.",
  },
  {
    id: nid("dep"),
    sourceTaskId: "task-101",
    targetTaskId: "task-105",
    type: "precedes",
    status: "resolved",
    risk: "low",
    reason:
      "OAuth2 onboarding flow was a prerequisite for service catalog authentication. Now resolved.",
  },
  {
    id: nid("dep"),
    sourceTaskId: "task-103",
    targetTaskId: "task-115",
    type: "depends_on",
    status: "at_risk",
    risk: "high",
    reason:
      "Audit trail must be in place before e2e tests can validate audit log entries in the test suite.",
  },
];

export const DEFAULT_ACTION_PLAN_ITEMS: ActionPlanItem[] = [
  {
    id: nid("api"),
    title: "Resolve Redis cluster provisioning",
    owner: "James Liu",
    dueDate: "2026-06-24",
    priority: "critical",
    source: "blocker",
    status: "in_progress",
    linkedTaskIds: ["task-102", "task-109"],
    linkedBlockerIds: ["blocker-105"],
  },
  {
    id: nid("api"),
    title: "Obtain compliance review template from Legal",
    owner: "Diana Reyes",
    dueDate: "2026-07-01",
    priority: "critical",
    source: "blocker",
    status: "planned",
    linkedTaskIds: ["task-103", "task-104"],
    linkedBlockerIds: ["blocker-104"],
  },
  {
    id: nid("api"),
    title: "Complete OAuth2 implementation review fixes",
    owner: "Priya Kapoor",
    dueDate: "2026-06-28",
    priority: "high",
    source: "task",
    status: "in_progress",
    linkedTaskIds: ["task-101"],
    linkedBlockerIds: [],
  },
  {
    id: nid("api"),
    title: "Define API contract for namespace provisioning",
    owner: "James Liu",
    dueDate: "2026-06-25",
    priority: "medium",
    source: "task",
    status: "planned",
    linkedTaskIds: ["task-106"],
    linkedBlockerIds: [],
  },
  {
    id: nid("api"),
    title: "Finalize SIEM vendor selection",
    owner: "Marcus Okonkwo",
    dueDate: "2026-06-27",
    priority: "high",
    source: "blocker",
    status: "planned",
    linkedTaskIds: ["task-103"],
    linkedBlockerIds: ["blocker-106"],
  },
  {
    id: nid("api"),
    title: "Create load testing plan and scripts",
    owner: "James Liu",
    dueDate: "2026-06-30",
    priority: "high",
    source: "task",
    status: "planned",
    linkedTaskIds: ["task-109"],
    linkedBlockerIds: [],
  },
];

export function createInitialProjectWorkState(): ProjectWorkState {
  return {
    project: { ...DEFAULT_PROJECT },
    tasks: DEFAULT_TASKS.map((t) => ({ ...t })),
    blockers: DEFAULT_BLOCKERS.map((b) => ({ ...b })),
    dependencies: DEFAULT_DEPENDENCIES.map((d) => ({ ...d })),
    actionPlanItems: DEFAULT_ACTION_PLAN_ITEMS.map((a) => ({ ...a })),
    artifacts: [],
    activityLog: [],
    selectedTaskId: null,
    selectedBlockerId: null,
    expandedArtifactId: null,
  };
}
