import type { StudioShowcaseAsset } from "./showcase-types";

// Filenames are R2 object names only (bucket: ethen/videos). Resolve full
// URLs at render time via getShowcaseAssetUrl() — never hardcode the host here.
export const STUDIO_SHOWCASE_ASSETS: StudioShowcaseAsset[] = [
  // ── Hero ──────────────────────────────────────────────────────────────
  {
    id: "hero-06c6fff7",
    type: "video",
    title: "Cinematic Motion Study",
    description: "A premium motion example for the Cinema Studio section.",
    section: "hero",
    filename: "06c6fff7-3244-42be-b0ba-ac26919f4143.mp4",
    posterFilename: "videoframe_1358.png",
    aspectRatio: "16/9",
    tags: ["hero", "cinema", "video"],
    appSlug: "image-to-video",
    ctaLabel: "Open Cinema Studio",
    status: "mock-preview",
    priority: true,
  },
  {
    id: "hero-0ad7a436",
    type: "video",
    title: "Create Image to Video",
    description: "Turn a single still into a moving shot.",
    section: "hero",
    filename: "0ad7a436-9a7d-4391-bf3a-ba1a400d6218.mp4",
    aspectRatio: "16/9",
    tags: ["hero", "video"],
    appSlug: "image-to-video",
    ctaLabel: "Open Image to Video",
    status: "mock-preview",
    priority: true,
  },
  {
    id: "hero-hf-20260313",
    type: "image",
    title: "Create Image",
    description: "Generate a still from a single prompt.",
    section: "hero",
    filename: "hf_20260313_150735_0b3401a1-0031-45fa-9402-808bc8315fbf.png",
    aspectRatio: "4/5",
    tags: ["hero", "image"],
    appSlug: "create-image",
    ctaLabel: "Open Create Image",
    status: "mock-preview",
    priority: true,
  },
  {
    id: "hero-af43f527",
    type: "video",
    title: "AI Influencer Concept",
    description: "A character concept for the AI Influencer studio.",
    section: "hero",
    filename: "af43f527-9aef-455d-85c2-56e96ef5dbcd.mp4",
    aspectRatio: "9/16",
    tags: ["hero", "influencer", "video"],
    appSlug: "ai-influencer",
    ctaLabel: "Open AI Influencer",
    status: "setup-required",
    priority: true,
  },

  // ── Cinema ────────────────────────────────────────────────────────────
  {
    id: "cinema-7afe56ae",
    type: "video",
    title: "Cinematic Shot Study",
    description: "A moody AI motion concept for Cinema Studio.",
    section: "cinema",
    filename: "7afe56ae-3748-450f-8f5a-82cc8fedac8f.mp4",
    posterFilename: "videoframe_1467.png",
    aspectRatio: "16/9",
    tags: ["cinema", "video"],
    appSlug: "cinema-studio",
    ctaLabel: "Open Cinema Studio",
    status: "mock-preview",
  },
  {
    id: "cinema-25b45f96",
    type: "video",
    title: "Cinema Studio Reel",
    section: "cinema",
    filename: "25b45f96-2d91-466f-8ed8-ecfc3dc50b70.mp4",
    aspectRatio: "21/9",
    tags: ["cinema", "video"],
    appSlug: "cinema-studio",
    ctaLabel: "Open Cinema Studio",
    status: "mock-preview",
  },
  {
    id: "cinema-bpd8fow6",
    type: "video",
    title: "Cinematic Camera Move",
    section: "cinema",
    filename: "B_pd8FOw6JiLYbK4.mp4",
    aspectRatio: "16/9",
    tags: ["cinema", "video"],
    appSlug: "cinematic-cameras",
    ctaLabel: "Open Cinematic Cameras",
    status: "mock-preview",
  },
  {
    id: "cinema-180bd3d3",
    type: "video",
    title: "Cinema Shot Builder Sample",
    section: "cinema",
    filename: "180bd3d3-3ca9-4b63-bfa9-24d5afe16c67.mp4",
    aspectRatio: "16/9",
    tags: ["cinema", "video"],
    appSlug: "cinema-shot-builder",
    ctaLabel: "Open Cinema Shot Builder",
    status: "mock-preview",
  },
  {
    id: "cinema-4ce95288",
    type: "video",
    title: "Cinema Motion Sample",
    section: "cinema",
    filename: "4ce95288-d551-489d-879c-f4ff4ad678e3.mp4",
    aspectRatio: "16/9",
    tags: ["cinema", "video"],
    appSlug: "cinema-studio",
    ctaLabel: "Open Cinema Studio",
    status: "mock-preview",
  },
  {
    id: "cinema-hf-20260409-094417",
    type: "video",
    title: "Cinema Motion Sample",
    section: "cinema",
    filename: "hf_20260409_094417_ba8bf934-a387-4bf5-8a24-f34be2a65d46_min.mp4",
    aspectRatio: "16/9",
    tags: ["cinema", "video"],
    appSlug: "cinema-studio",
    ctaLabel: "Open Cinema Studio",
    status: "mock-preview",
  },
  {
    id: "cinema-hf-20260413-121933",
    type: "video",
    title: "Cinema Motion Sample",
    section: "cinema",
    filename: "hf_20260413_121933_7dfa9582-a536-4a83-9041-ee5aa102ff8c.mp4",
    aspectRatio: "16/9",
    tags: ["cinema", "video"],
    appSlug: "cinema-studio",
    ctaLabel: "Open Cinema Studio",
    status: "mock-preview",
  },
  {
    id: "cinema-hf-20260415-001819",
    type: "video",
    title: "Cinema Motion Sample",
    section: "cinema",
    filename: "hf_20260415_001819_f11fd2c4-6297-40b4-9b18-3a2c65c25c2a.mp4",
    aspectRatio: "16/9",
    tags: ["cinema", "video"],
    appSlug: "cinema-studio",
    ctaLabel: "Open Cinema Studio",
    status: "mock-preview",
  },

  // ── Image ─────────────────────────────────────────────────────────────
  {
    id: "image-hf-20260314",
    type: "image",
    title: "Image Experiment",
    section: "image",
    filename: "hf_20260314_194923_c279d800-65c9-4711-bc6a-2715bda503e2.png",
    aspectRatio: "4/5",
    tags: ["image"],
    appSlug: "create-image",
    ctaLabel: "Open Create Image",
    status: "mock-preview",
  },
  {
    id: "image-hf-20260421",
    type: "image",
    title: "Surreal World Concept",
    section: "image",
    filename: "hf_20260421_162100_a9cb557d-1397-42c1-ac16-499c09042ea5.png",
    aspectRatio: "1/1",
    tags: ["image", "surreal"],
    appSlug: "create-image",
    ctaLabel: "Open Create Image",
    status: "mock-preview",
  },
  {
    id: "image-videoframe-1552",
    type: "image",
    title: "Poster Concept Frame",
    section: "image",
    filename: "videoframe_1552.png",
    aspectRatio: "4/5",
    tags: ["image", "poster"],
    appSlug: "create-image",
    ctaLabel: "Open Create Image",
    status: "mock-preview",
  },
  {
    id: "image-videoframe-1567",
    type: "image",
    title: "Editorial Still",
    section: "image",
    filename: "videoframe_1567.png",
    aspectRatio: "16/9",
    tags: ["image"],
    appSlug: "image-upscale",
    ctaLabel: "Open Image Upscale",
    status: "mock-preview",
  },
  {
    id: "image-hf-20260422-212327",
    type: "image",
    title: "Image Experiment",
    section: "image",
    filename: "hf_20260422_212327_3e910da2-86aa-4fac-adbe-4215fe2110a5.png",
    aspectRatio: "4/5",
    tags: ["image"],
    appSlug: "create-image",
    ctaLabel: "Open Create Image",
    status: "mock-preview",
  },
  {
    id: "image-hf-20260422-215112",
    type: "image",
    title: "Image Experiment",
    section: "image",
    filename: "hf_20260422_215112_09f9313d-4c93-40d5-8d5b-e6a502fa93c1.png",
    aspectRatio: "1/1",
    tags: ["image"],
    appSlug: "create-image",
    ctaLabel: "Open Create Image",
    status: "mock-preview",
  },
  {
    id: "image-hf-20260422-215626",
    type: "image",
    title: "Image Experiment",
    section: "image",
    filename: "hf_20260422_215626_8f188629-c5bb-441a-a0fe-a0be4d976fc6.png",
    aspectRatio: "4/5",
    tags: ["image"],
    appSlug: "create-image",
    ctaLabel: "Open Create Image",
    status: "mock-preview",
  },

  // ── Marketing ─────────────────────────────────────────────────────────
  {
    id: "marketing-9342e910",
    type: "video",
    title: "Marketing Studio Reel",
    description: "Turn one product idea into ads and campaign assets.",
    section: "marketing",
    filename: "9342e910-75cf-4df5-aaec-379cbb9eaa73.mp4",
    aspectRatio: "16/9",
    tags: ["marketing", "video"],
    appSlug: "product-url-to-ad",
    ctaLabel: "Open Marketing Studio",
    status: "mock-preview",
  },
  {
    id: "marketing-hf-20260422-123132",
    type: "image",
    title: "Product Visual Concept",
    section: "marketing",
    filename: "hf_20260422_123132_46507b07-1818-46b3-be30-274c71b219d7.png",
    aspectRatio: "4/5",
    tags: ["marketing", "product"],
    appSlug: "product-url-to-ad",
    ctaLabel: "Open Marketing Studio",
    status: "mock-preview",
  },

  // ── Influencer ────────────────────────────────────────────────────────
  {
    id: "influencer-b2aaeb88",
    type: "video",
    title: "AI Influencer Character Reel",
    section: "influencer",
    filename: "b2aaeb88-32cb-469e-8dd7-2e97036a7997.mp4",
    aspectRatio: "9/16",
    tags: ["influencer", "video"],
    appSlug: "ai-influencer",
    ctaLabel: "Open AI Influencer",
    status: "setup-required",
  },
  {
    id: "influencer-hf-20260422-132318",
    type: "image",
    title: "Character Look Concept",
    section: "influencer",
    filename: "hf_20260422_132318_ba7fc1f7-9011-47ca-bd0d-af690c4cf934.png",
    aspectRatio: "4/5",
    tags: ["influencer", "character"],
    appSlug: "soul-id-character",
    ctaLabel: "Open Character Studio",
    status: "mock-preview",
  },
  {
    id: "influencer-hf-20260413-134418",
    type: "video",
    title: "Character Motion Sample",
    section: "influencer",
    filename: "hf_20260413_134418_6d688d5f-a19e-453c-95ac-72829a69a19b.mp4",
    aspectRatio: "9/16",
    tags: ["influencer", "video"],
    appSlug: "ai-influencer",
    ctaLabel: "Open AI Influencer",
    status: "setup-required",
  },
  {
    id: "influencer-hf-20260421-231701",
    type: "video",
    title: "Character Motion Sample",
    section: "influencer",
    filename: "hf_20260421_231701_b2dc3bd1-2cc8-45a8-b162-a0eeee07ae2d.mp4",
    aspectRatio: "9/16",
    tags: ["influencer", "video"],
    appSlug: "ai-influencer",
    ctaLabel: "Open AI Influencer",
    status: "setup-required",
  },

  // ── Games ─────────────────────────────────────────────────────────────
  {
    id: "games-b868900a",
    type: "video",
    title: "Game Asset Motion Sample",
    section: "games",
    filename: "b868900a-7b71-474b-bd6b-b7ea9597fa79.mp4",
    aspectRatio: "1/1",
    tags: ["games", "video"],
    appSlug: "game-asset-generator",
    ctaLabel: "Open Game Asset Generator",
    status: "mock-preview",
  },
  {
    id: "games-videoframe-1836",
    type: "image",
    title: "Game Environment Frame",
    section: "games",
    filename: "videoframe_1836.png",
    aspectRatio: "16/9",
    tags: ["games"],
    appSlug: "background-generator",
    ctaLabel: "Open Background Generator",
    status: "mock-preview",
  },
  {
    id: "games-videoframe-1913",
    type: "image",
    title: "Game Icon Pack Frame",
    section: "games",
    filename: "videoframe_1913.png",
    aspectRatio: "1/1",
    tags: ["games", "icon"],
    appSlug: "icon-pack-generator",
    ctaLabel: "Open Icon Pack Generator",
    status: "mock-preview",
  },
  {
    id: "games-videoframe-1397",
    type: "image",
    title: "Game Asset Concept Frame",
    section: "games",
    filename: "videoframe_1397.png",
    aspectRatio: "1/1",
    tags: ["games"],
    appSlug: "game-asset-generator",
    ctaLabel: "Open Game Asset Generator",
    status: "mock-preview",
  },
  {
    id: "games-hf-20260421-235853",
    type: "video",
    title: "Game Asset Motion Sample",
    section: "games",
    filename: "hf_20260421_235853_5cf68d17-44dc-459c-936e-7834cf79984f.mp4",
    aspectRatio: "1/1",
    tags: ["games", "video"],
    appSlug: "game-asset-generator",
    ctaLabel: "Open Game Asset Generator",
    status: "mock-preview",
  },

  // ── Canvas ────────────────────────────────────────────────────────────
  {
    id: "canvas-d06fe04e",
    type: "video",
    title: "Canvas Workflow Sample",
    section: "canvas",
    filename: "d06fe04e-9a74-4ef3-94f3-a8a9916ba249.mp4",
    aspectRatio: "16/9",
    tags: ["canvas", "video"],
    appSlug: "canvas",
    ctaLabel: "Try Canvas",
    status: "mock-preview",
  },
  {
    id: "canvas-videoframe-1918",
    type: "image",
    title: "Moodboard Frame",
    section: "canvas",
    filename: "videoframe_1918.png",
    aspectRatio: "4/5",
    tags: ["canvas", "moodboard"],
    appSlug: "moodboard",
    ctaLabel: "Open Moodboard",
    status: "mock-preview",
  },

  // ── Supercomputer ─────────────────────────────────────────────────────
  // No app slug exists for "supercomputer" in lib/media/apps.ts — the
  // Supercomputer nav section is a placeholder (see app-registry.ts), so
  // appSlug is intentionally left unset here.
  {
    id: "supercomputer-epwafplh",
    type: "video",
    title: "Supercomputer Concept Reel",
    description: "One agent layer for your entire creative stack.",
    section: "supercomputer",
    filename: "EPWAFPlHbdRWzqUc.mp4",
    aspectRatio: "21/9",
    tags: ["supercomputer", "video"],
    ctaLabel: "Try Supercomputer",
    status: "coming-soon",
  },
  {
    id: "supercomputer-videoframe-1945",
    type: "image",
    title: "Supercomputer Visual Concept",
    section: "supercomputer",
    filename: "videoframe_1945.png",
    aspectRatio: "16/9",
    tags: ["supercomputer"],
    ctaLabel: "Try Supercomputer",
    status: "coming-soon",
  },

  // ── Video (explore-more / general video apps) ────────────────────────
  {
    id: "video-508c2da7",
    type: "video",
    title: "Create Video Sample",
    section: "video",
    filename: "508c2da7-2f1d-4109-8090-d300feac8c73.mp4",
    aspectRatio: "16/9",
    tags: ["video"],
    appSlug: "create-video",
    ctaLabel: "Open Create Video",
    status: "mock-preview",
  },
  {
    id: "video-hf-20260409-094612",
    type: "video",
    title: "Video Worlds Sample",
    section: "video",
    filename: "hf_20260409_094612_2b122af8-b47a-4518-9d91-9675dd8e3f41_min.mp4",
    aspectRatio: "16/9",
    tags: ["video"],
    appSlug: "create-video",
    ctaLabel: "Open Create Video",
    status: "mock-preview",
  },
  {
    id: "video-hf-20260413-131601",
    type: "video",
    title: "Video Worlds Sample",
    section: "video",
    filename: "hf_20260413_131601_e29e767d-fe44-4b42-a751-01b178692f67.mp4",
    aspectRatio: "16/9",
    tags: ["video"],
    appSlug: "video-upscale",
    ctaLabel: "Open Video Upscale",
    status: "mock-preview",
  },
  {
    id: "video-hf-20260413-132040",
    type: "video",
    title: "Video Worlds Sample",
    section: "video",
    filename: "hf_20260413_132040_3db6758b-7eef-4046-87e1-ec81097c126e.mp4",
    aspectRatio: "16/9",
    tags: ["video"],
    appSlug: "create-video",
    ctaLabel: "Open Create Video",
    status: "mock-preview",
  },
  {
    id: "video-hf-20260422-001333",
    type: "video",
    title: "Video Worlds Sample",
    section: "video",
    filename: "hf_20260422_001333_36103dd7-9f8a-414f-9b5f-23683f07f703.mp4",
    aspectRatio: "16/9",
    tags: ["video"],
    appSlug: "create-video",
    ctaLabel: "Open Create Video",
    status: "mock-preview",
  },
  {
    id: "video-videoframe-2189",
    type: "image",
    title: "Video Frame Still",
    section: "video",
    filename: "videoframe_2189.png",
    aspectRatio: "16/9",
    tags: ["video"],
    appSlug: "video-upscale",
    ctaLabel: "Open Video Upscale",
    status: "mock-preview",
  },
  {
    id: "video-videoframe-3209",
    type: "image",
    title: "Video Frame Still",
    section: "video",
    filename: "videoframe_3209.png",
    aspectRatio: "16/9",
    tags: ["video"],
    status: "mock-preview",
  },
  {
    id: "video-videoframe-9454",
    type: "image",
    title: "Video Frame Still",
    section: "video",
    filename: "videoframe_9454.png",
    aspectRatio: "16/9",
    tags: ["video"],
    status: "mock-preview",
  },
];

export function getShowcaseAssetsBySection(
  section: StudioShowcaseAsset["section"],
): StudioShowcaseAsset[] {
  return STUDIO_SHOWCASE_ASSETS.filter((asset) => asset.section === section);
}

export function getShowcaseAssetById(id: string): StudioShowcaseAsset | undefined {
  return STUDIO_SHOWCASE_ASSETS.find((asset) => asset.id === id);
}
